//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MusicPlayer2.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDD_MUSICPLAYER2_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDD_SET_PATH_DIALOG             133
#define IDD_FIND_DIALOG                 136
#define IDD_OPTIONS_DIALOG              138
#define IDD_LYRIC_SETTING_DIALOG        140
#define IDD_APPEREANCE_SETTING_DLG      142
#define IDD_PROPERTY_DIALOG             145
#define IDI_PREVIOUS                    151
#define IDI_PLAY_PAUSE                  152
#define IDI_NEXT1                       154
#define IDI_PLAY                        155
#define IDI_PAUSE                       156
#define IDI_STOP                        158
#define IDD_MESSAGE_DIALOG              159
#define IDD_MINI_DIALOG                 164
#define IDD_LYRIC_EDIT_DIALOG           171
#define IDD_DATA_SETTINGS_DIALOG        173
#define IDD_LYRIC_DOWNLOAD_DIALOG       176
#define IDD_LYRIC_BATCH_DOWN_DIALOG     178
#define IDD_EQUALIZER_DIALOG            181
#define IDD_SOUND_EFFECT_DIALOG         183
#define IDD_REVERB_DIALOG               185
#define IDB_DEFAULT_COVER               190
#define IDB_CORTANA_BLACK               191
#define IDB_CORTANA_WHITE               192
#define IDR_LYRIC_EDIT_TOOLBAR          193
#define IDI_ADD_TAG                     195
#define IDI_REPLACE_TAG                 196
#define IDI_DELETE_TAG                  197
#define IDI_SAVE                        198
#define IDI_FIND                        199
#define IDI_REPLACE                     200
#define IDI_FF                          201
#define IDI_REW                         202
#define IDD_COVER_DOWNLOAD_DIALOG       206
#define IDD_FORMAT_CONVERT_DIALOG       208
#define IDD_MP3_ENCODE_CFG_DIALOG       210
#define IDD_OGG_ENCODE_CFG_DIALOG       212
#define IDD_WMA_ENCODE_CFG_DIALOG       214
#define IDD_TAG_EDIT_DIALOG             217
#define IDD_PLAY_SETTING_DIALOG         221
#define IDD_SUPPORT_FORMAT_DIALOG       222
#define IDI_DEFAULT_COVER               224
#define IDI_SKIN                        225
#define IDI_EQ                          226
#define IDI_SETTING                     227
#define IDI_LOOP_TRACK                  228
#define IDI_LOOP_PLAYLIST               229
#define IDI_PLAY_ORDER                  230
#define IDI_PLAY_SHUFFLE                231
#define IDI_SKIN_D                      232
#define IDI_EQ_D                        233
#define IDI_SETTING_D                   234
#define IDI_LOOP_TRACK_D                235
#define IDI_LOOP_PLAYLIST_D             236
#define IDI_PLAY_ORDER_D                237
#define IDI_PLAY_SHUFFLE_D              238
#define IDI_MINI                        239
#define IDI_MINI_D                      240
#define IDD_HOT_KEY_SETTINGS_DIALOG     241
#define IDI_SONG_INFO                   244
#define IDI_SONG_INFO_D                 245
#define IDI_SELECT_FOLDER               246
#define IDI_SELECT_FOLDER_D             247
#define IDI_PLAYLIST                    248
#define IDI_PLAYLIST_D                  249
#define IDI_FIND_SONGS                  362
#define IDI_FIND_SONGS_D                363
#define IDI_FULL_SCREEN                 364
#define IDI_FULL_SCREEN_D               365
#define IDI_FULL_SCREEN1                366
#define IDI_FULL_SCREEN1_D              367
#define IDD_LISTEN_TIME_STATISTICS_DLG  368
#define IDD_DONATE_DIALOG               370
#define IDB_DONATE                      372
#define IDI_MENU                        375
#define IDI_MENU_D                      376
#define IDD_MEDIA_LIB_DIALOG            378
#define IDD_SELECT_PLAYLIST_DIALOG      382
#define IDD_INPUT_DLG                   384
#define IDI_FILE_ICON                   386
#define IDI_MEDIA_LIB                   387
#define IDI_MEDIA_LIB_D                 388
#define IDD_FILE_RELATE_DIALOG          389
#define IDD_TEST_DIALOG                 391
#define IDC_DRAG_CURSOR                 391
#define IDI_FAVOURITE                   392
#define IDI_FAVOURITE_D                 393
#define IDI_HEART                       394
#define IDI_CLOSE_D                     396
#define IDI_LOCK_D                      397
#define IDI_DOUBLE_LINE_D               398
#define IDI_EDIT_D                      401
#define IDI_ADD_D                       402
#define IDD_MEDIA_CLASSIFY_DIALOG       412
#define IDI_ALBUM_D                     416
#define IDI_ARTIST_D                    417
#define IDI_YEAR_D                      418
#define IDD_FOLDER_EXPLORE_DIALOG       419
#define IDI_FOLDER_EXPLORE_D            422
#define IDI_EXPLORE_FOLDER              423
#define IDD_MEDIA_LIB_SETTING_DIALOG    424
#define IDD_ADD_TO_PLAYLIST_DIALOG      426
#define IDD_ALL_MEDIA_DIALOG            428
#define IDI_GENRE_D                     431
#define IDI_LYRIC_DELAY_D               432
#define IDI_LYRIC_FORWARD_D             433
#define IDI_RECENT_SONG_D               434
#define IDI_FILE_PLAYLIST               435
#define IDB_DONATE_WECHAT               436
#define IDI_STOP_NEW                    437
#define IDI_STOP_NEW_D                  438
#define IDI_PREVIOUS_NEW                439
#define IDI_PREVIOUS_NEW_D              440
#define IDI_PLAY_NEW                    441
#define IDI_PLAY_NEW_D                  442
#define IDI_PAUSE_NEW                   443
#define IDI_PAUSE_NEW_D                 444
#define IDI_NEXT_NEW                    445
#define IDI_NEXT_NEW_D                  446
#define IDR_LICENSE                     448
#define IDI_SAVE_NEW_D                  449
#define IDI_MUSIC_D                     450
#define IDI_FILE_RELATE_D               451
#define IDI_ONLINE_D                    452
#define IDI_PLAY_PAUSE_D                453
#define IDI_CONVERT_D                   454
#define IDI_DOWNLOAD_D                  455
#define IDI_DOWNLOAD1_D                 456
#define IDI_HELP_D                      457
#define IDI_FF_NEW_D                    458
#define IDI_REW_NEW_D                   459
#define IDI_SAVE_AS_D                   460
#define IDI_PLAYLIST_FLOAT_D            461
#define IDI_PLAYLIST_DOCK_D             462
#define IDI_STATISTICS_D                463
#define IDI_PIN_D                       464
#define IDI_EXIT_D                      465
#define IDI_ALBUM_COVER_D               466
#define IDI_DARK_MODE_D                 467
#define IDB_DEFAULT_ALBUM_COVER         469
#define IDD_LYRIC_RELATE_DIALOG         470
#define IDI_LYRIC_D                     472
#define IDI_APP_DARK                    473
#define IDI_APP_LIGHT                   474
#define IDB_NOTIFY_ICON_PREVIEW         475
#define IDB_NOTIFY_ICON_PREVIEW_LIGHT   476
#define IDI_DEFAULT_COVER_NOT_PLAYED    477
#define IDB_DEFAULT_ALBUM_COVER_NOT_PLAYED 478
#define IDR_ACCELERATOR1                479
#define IDD_CLEAN_UP_RANGE_DIALOG       480
#define IDI_PLAY_RANDOM                 484
#define IDI_PLAY_RANDOM_D               485
#define IDD_PROPERTY_PARENT_DIALOG      486
#define IDD_PROPERTY_ALBUM_COVER_DIALOG 488
#define IDI_OK_D                        491
#define IDD_TAG_MODE_SELECT_DIALOG      493
#define IDI_RENAME_D                    495
#define IDI_PLAY_TRACK                  498
#define IDI_PLAY_TRACK_D                499
#define IDI_APP_DEBUG                   500
#define IDD_PROPERTY_ADVANCED_DIALOG    501
#define IDI_TAG                         504
#define IDD_SELECT_ITEM_DIALOG          505
#define IDI_LOCATE_D                    507
#define IDI_STAR                        508
#define IDI_CLOSE                       534
#define IDI_MINIMIZE                    535
#define IDI_MINIMIZE_D                  536
#define IDI_MAXIMIZE                    537
#define IDI_MAXIMIZE_D                  538
#define IDI_RESTORE                     539
#define IDI_RESTORE_D                   540
#define IDR_COMPILE_TIME                540
#define IDI_VOLUME3_D                   541
#define IDI_VOLUME2_D                   542
#define IDI_VOLUME1_D                   543
#define IDI_VOLUME3                     544
#define IDI_VOLUME2                     545
#define IDI_VOLUME1                     546
#define IDI_VOLUME0                     547
#define IDI_VOLUME0_D                   548
#define IDI_EXPAND_D                    551
#define IDI_ADD                         552
#define IDI_SORT                        555
#define IDI_SORT_D                      556
#define IDI_DISPLAY_MODE                557
#define IDI_DISPLAY_MODE_D              558
#define IDI_LINK                        559
#define IDI_LINK_D                      560
#define IDI_UNLINK                      561
#define IDI_UNLINK_D                    562
#define IDI_INTERNAL_LYRIC_D            563
#define IDI_SPEED_UP_D                  564
#define IDI_SLOW_DOWN_D                 565
#define IDI_SHORTCUT_D                  566
#define IDI_SWITCH                      567
#define IDI_SWITCH_D                    568
#define IDI_LYRIC                       569
#define IDI_PLAYLIST_DOCK               570
#define IDI_HELP                        571
#define IDI_LIGHT_MODE                  573
#define IDD_FLAC_ENCODE_CFG_DIALOG      573
#define IDI_PLAY_AS_NEXT                575
#define IDI_PLAY_IN_PLAYLIST            576
#define IDI_COPY                        577
#define IDI_PLAY_IN_FOLDER              578
#define IDI_BITRATE                     579
#define IDI_REVERB                      580
#define IDI_HOT_KEY                     581
#define IDI_MINI_RESTORE                582
#define IDI_MINI_RESTORE_D              584
#define IDI_LOCATE                      585
#define IDI_EXPAND                      586
#define IDI_FIX_D                       587
#define IDR_ACKNOWLEDGEMENT             588
#define IDR_UI1                         589
#define IDR_UI2                         590
#define IDR_STRING_TABLE                591
#define IDI_UP_D                        592
#define IDR_MINI_UI0                    593
#define IDI_ARTIST                      594
#define IDI_ALBUM                       595
#define IDI_GENRE                       596
#define IDI_YEAR                        597
#define IDI_FILE_RELATE                 598
#define IDI_BITRATE_D                   599
#define IDI_STAR_D                      600
#define IDI_MORE_D                      601
#define IDR_CHINESE_PINGYIN             602
#define IDI_RECENT_SONG                 603
#define IDI_ALBUM_COVER                 605
#define IDI_REVERB_D                    607
#define IDI_PLAY_IN_PLAYLIST_D          608
#define IDI_NOW_PLAYING                 609
#define IDI_NOW_PLAYING_D               610
#define IDI_KARAOKE                     611
#define IDI_KARAOKE_D                   612
#define IDB_OWNER_DRAW_TITLEBAR_PREVIEW 613
#define IDB_SYSTEM_TITLEBAR_PREVIEW     614
#define IDI_REFRESH_D                   615
#define IDI_REFRESH                     616
#define IDI_NEW_FOLDER                  617
#define IDI_NEW_FOLDER_D                618
#define IDI_BACKGROUND_D                619
#define IDI_FOLDER_EXPLORE              620
#define IDI_TREE_COLLAPSED_D            621
#define IDI_TREE_EXPANDED_D             622
#define IDI_TREE_COLLAPSED              623
#define IDI_ICON2                       624
#define IDI_TREE_EXPANDED               624
#define IDD_UI_SEARCH_BOX_DIALOG        625
#define IDC_LIST1                       1002
#define IDC_PATH_LIST                   1002
#define IDC_LYRIC_DOWN_LIST1            1002
#define IDC_SONG_LIST1                  1002
#define IDC_EQU_STYLES_LIST             1002
#define IDC_OUTPUT_DEVICE_INFO_LIST     1002
#define IDC_HOT_KEY_LIST                1002
#define IDC_STATIC_VERSION              1003
#define IDC_TRACK_EDIT                  1009
#define IDC_FIND_BUTTON                 1012
#define IDC_PREVIOUS_BUTTON             1012
#define IDC_CLEAN_DATA_FILE_BUTTON      1012
#define IDC_SEARCH_BUTTON2              1012
#define IDC_ENCODER_CONFIG_BUTTON       1012
#define IDC_APPLY_BUTTON                1012
#define IDC_SET_BUTTON                  1012
#define IDC_SET_FONT                    1012
#define IDC_EXPORT_BUTTON               1012
#define IDC_PLAY_SELECTED               1012
#define IDC_NEW_PLAYLIST                1012
#define IDC_DONOT_RELATE_BUTTON         1012
#define IDC_DEFAULT_BUTTON              1012
#define IDC_SAVE_ALBUM_COVER_BUTTON     1012
#define IDC_GET_TAG_ONLINE_BUTTON       1012
#define IDC_TITLE_BUTTON                1012
#define IDC_OPEN_CONFIG_PATH_BUTTON     1012
#define IDC_NEXT_BUTTON                 1013
#define IDC_SET_FONT2                   1013
#define IDC_CLEAR_RECENT_PLAYED_LIST_BTN 1013
#define IDC_SHOW_OUT_ALBUM_COVER_CHK    1013
#define IDC_ARTIST_BUTTON               1013
#define IDC_ALBUM_BUTTON                1014
#define IDC_SET_FONT_BUTTON             1014
#define IDC_PLAYLIST_LIST               1015
#define IDC_TRACK_BUTTON                1015
#define IDC_FIND_EDIT                   1016
#define IDC_YEAR_BUTTON                 1016
#define IDC_FIND_LIST                   1017
#define IDC_GENRE_BUTTON                1017
#define IDC_FIND_RESULT_STATIC          1018
#define IDC_COMMENT_BUTTON              1018
#define IDC_PATH_EDIT                   1019
#define IDC_FIND_INFO_STATIC            1019
#define IDC_ORIGINAL_BUTTON             1019
#define IDC_PATH_STATIC                 1020
#define IDC_OPTIONS_TAB                 1024
#define IDC_STOP_WHEN_ERROR             1025
#define IDC_FOLLOW_SYSTEM_COLOR_CHECK   1025
#define IDC_FIND_FILE_CHECK             1025
#define IDC_SKIP_EXIST_CHECK            1025
#define IDC_DOWNLOAD_TRANSLATE_CHECK1   1025
#define IDC_ENABLE_EQU_CHECK            1025
#define IDC_ENABLE_REVERB_CHECK         1025
#define IDC_JOINT_STEREO_CHECK          1025
#define IDC_COPY_TAG_CHECK              1025
#define IDC_HOT_KEY_ENABLE_CHECK        1025
#define IDC_SHOW_SPECTRUM_IN_CORTANA    1025
#define IDC_SELECT_ALL_CHECK            1025
#define IDC_CLASSIFY_OTHER_CHECK        1025
#define IDC_FUZZY_MATCH_CHECK           1025
#define IDC_SPECIFY_PARA_CHECK          1025
#define IDC_KARAOKE_DISP                1026
#define IDC_FIND_TITLE_CHECK            1026
#define IDC_DOWNLOAD_TRASNLATE_CHECK2   1026
#define IDC_SHOW_ALBUM_COVER_CHECK      1026
#define IDC_COVER_AUTO_DOWNLOAD_CHECK   1026
#define IDC_COPY_ALBUM_COVER_CHECK      1026
#define IDC_AUTO_PLAY_WHEN_START_CHECK  1026
#define IDC_ENABLE_GLOBAL_MULTIMEDIA_KEY_CHECK 1026
#define IDC_UPDATE_MEDIA_LIB_CHK        1026
#define IDC_FIND_ARTIST_CHECK           1027
#define IDC_LYRIC_FUZZY_MATCH           1027
#define IDC_SHOW_SPECTRUM_CHECK         1027
#define IDC_LYRIC_AUTO_DOWNLOAD_CHECK   1027
#define IDC_SHOW_PLAY_STATE_ICON_CHECK  1027
#define IDC_OPEN_TARGET_DIR_CHECK       1027
#define IDC_FIND_ALBUM_CHECK            1028
#define IDC_SHOW_LYRIC_IN_CORTANA       1028
#define IDC_DOWNLOAD_WHEN_TAG_FULL_CHECK 1028
#define IDC_ARTIST_CHECK                1028
#define IDC_SHOW_NEXT_CHECK             1028
#define IDC_CONTINUE_WHEN_SWITCH_PLAYLIST_CHECK 1028
#define IDC_LYRIC_PATH_EDIT             1029
#define IDC_BITRATE_CHECK               1029
#define IDC_SHOW_FPS_CHECK              1029
#define IDC_ALL_CHECK                   1030
#define IDC_FONT_SIZE_EDIT2             1030
#define IDC_SLIDER1                     1031
#define IDC_TRANSPARENT_SLIDER          1031
#define IDC_RECENT_CHECK                1031
#define IDC_SLIDER2                     1032
#define IDC_RATING_CHECK                1032
#define IDC_TRANSPARENT_STATIC          1033
#define IDC_SLIDER3                     1033
#define IDC_FOLDER_EXPLORE_CHECK        1033
#define IDC_FILE_NAME_EDIT              1034
#define IDC_SLIDER4                     1034
#define IDC_FILE_PATH_EDIT              1035
#define IDC_SHOW_TASKBAR_PROGRESS       1035
#define IDC_SLIDER5                     1035
#define IDC_ALBUM_COVER_BACKGROUND_CHECK 1035
#define IDC_CHECK_UPDATE_CHECK          1035
#define IDC_ADD_NUMBER_CHECK            1035
#define IDC_DISABLE_DRAGE_SORT_CHECK    1035
#define IDC_SHOW_LYRIC_TRANSLATE_CHECK  1035
#define IDC_FILE_TYPE_EDIT              1036
#define IDC_SLIDER6                     1036
#define IDC_SONG_LENGTH_EDIT            1037
#define IDC_SYSLINK1                    1037
#define IDC_SLIDER7                     1037
#define IDC_FILE_SIZE_EDIT              1038
#define IDC_SLIDER8                     1038
#define IDC_BIT_RATE_EDIT               1039
#define IDC_SLIDER9                     1039
#define IDC_SET_PROGRESS_COLOR_BUTTON   1040
#define IDC_TITEL_EDIT                  1040
#define IDC_SLIDER10                    1040
#define IDC_COLOR_STATIC                1041
#define IDC_ARTIST_EDIT                 1041
#define IDC_COLOR_STATIC2               1042
#define IDC_ITEM_STATIC                 1042
#define IDC_SAMPLE_FREQ                 1042
#define IDC_COLOR_STATIC3               1043
#define IDC_ALBUM_EDIT                  1043
#define IDC_COLOR_STATIC4               1044
#define IDC_HELP_EDIT                   1044
#define IDC_LYRIC_FILE_EDIT             1044
#define IDC_COLOR_STATIC5               1045
#define IDC_TAG_TYPE_STATIC             1045
#define IDC_COLOR_STATIC6               1046
#define IDC_BITS_DIPTH                  1046
#define IDC_COLOR_STATIC7               1047
#define IDC_CHANNELS                    1047
#define IDC_COLOR_STATIC8               1048
#define IDC_YEAR_EDIT                   1050
#define IDC_COMMENT_EDIT                1052
#define IDC_EDIT1                       1061
#define IDC_PLAYLIST_ITEM_HEIGHT_EDIT   1061
#define IDC_LYRIC_PATH_EDIT2            1065
#define IDC_ARTIST_EDIT1                1065
#define IDC_FILE_TOO_SHORT_SEC_EDIT     1065
#define IDC_SIZE_STATIC                 1067
#define IDC_TITLE_EDIT1                 1069
#define IDC_DOWNLOAD_SELECTED           1070
#define IDC_START_DOWNLOAD              1071
#define IDC_COMBO1                      1072
#define IDC_INFO_STATIC                 1073
#define IDC_ABR_RATE_COMBO              1073
#define IDC_HIGHLIGHT_GRADIENT_COMBO    1073
#define IDC_STATIC_INFO                 1074
#define IDC_LIST2                       1075
#define IDC_STATIC1                     1076
#define IDC_SAVE_TO_SONG_FOLDER         1077
#define IDC_SAVE_TO_LYRIC_FOLDER        1078
#define IDC_FIND_ALL_PLAYLIST_RADIO     1078
#define IDC_MCI_RADIO                   1078
#define IDC_COPY_RADIO                  1078
#define IDC_SAVE_TO_ALBUM_FOLDER2       1078
#define IDC_COMBO2                      1079
#define IDC_SAVE_TO_SONG_FOLDER3        1079
#define IDC_SAVE_TO_SONG_FOLDER1        1080
#define IDC_SAVE_TO_ALBUM_FOLDER3       1080
#define IDC_SAVE_TO_LYRIC_FOLDER1       1081
#define IDC_SELECTED_SAVE_AS            1082
#define IDC_SAVE_TO_FILE_BUTTON         1082
#define IDC_BROWSE_BUTTON               1082
#define IDC_DEFAULT_STYLE               1082
#define IDC_MEDIA_LIB_SETTINGS_BTN      1082
#define IDC_RESTORE_DEFAULT_BUTTON      1082
#define IDC_LOCAL_SEARCH_BUTTON         1082
#define IDC_GET_TAG_FROM_FILE_NAME_BUTTON 1082
#define IDC_REFRESH_MEDIA_LIB_BUTTON    1082
#define IDC_TAB1                        1083
#define IDC_REVERB_MIX_SLIDER           1084
#define IDC_REVERB_TIME_SLIDER          1085
#define IDC_REVERB_MIX_STATIC           1086
#define IDC_REVERB_TIME_STATIC          1087
#define IDC_SYSLINK2                    1088
#define IDC_LICENSE_SYSLINK             1089
#define IDC_SPECTRUM_HEIGHT_SLIDER      1090
#define IDC_SPECTRUM_HEIGHT_STATIC      1091
#define IDC_BACKGROUND_TRANSPARENCY_SLIDER 1092
#define IDC_FIND_CURRENT_PLAYLIST_RADIO 1093
#define IDC_BACKGROUND_TRANSPARENCY_STATIC 1093
#define IDC_GENRE_COMBO                 1094
#define IDC_GAUSS_BLURE_RADIUS_SLIDER   1094
#define IDC_LYRIC_DOUBLE_LINE_CHECK     1095
#define IDC_USE_OUT_IMAGE_CHECK         1095
#define IDC_SOUND_FADE_CHECK            1095
#define IDC_CHANGE_FREQ_CHECK           1095
#define IDC_INSERT_BEGIN_CHECK          1095
#define IDC_START_CONVERT_BUTTON        1096
#define IDC_GAUSS_BLUR_RADIUS_STATIC    1096
#define IDC_KEEP_DISPLAY_CHECK          1096
#define IDC_BROWSE_BUTTON1              1096
#define IDC_GET_TAG_FROM_LYRIC_BUTTON   1096
#define IDC_STATISTICS_INFO_BUTTON      1096
#define IDC_ALBUM_FIT_COMBO             1097
#define IDC_LYRIC_DOUBLE_LINE_CHECK2    1097
#define IDC_OPEN_FOLDER                 1098
#define IDC_LOCK_DESKTOP_LYRIC_CHECK    1098
#define IDC_CORTANA_COLOR_COMBO         1099
#define IDC_SHOW_ALBUM_COVER_IN_CORTANA 1101
#define IDC_CORTANA_ICON_DEAT_CHECK     1102
#define IDC_SEARCH_EDIT                 1103
#define IDC_SHOW_LYRIC_IN_CORTANA2      1103
#define IDC_DEFAULT_COVER_NAME_EDIT     1104
#define IDC_COVER_DOWN_LIST             1105
#define IDC_SEARCH_BUTTON               1106
#define IDC_TITLE_EDIT                  1107
#define IDC_GITHUB_SYSLINK              1108
#define IDC_SF2_PATH_EDIT               1109
#define IDC_DONATE_SYSLINK              1109
#define IDC_OUT_FORMAT_COMBO            1110
#define IDC_OUT_DIR_EDIT                1111
#define IDC_CBR_RADIO                   1112
#define IDC_OUT_NAME_EDIT               1112
#define IDC_ABR_RADIO                   1113
#define IDC_CBR_RADIO2                  1113
#define IDC_VBR_RADIO                   1114
#define IDC_USER_CHECK                  1115
#define IDC_CBR_RATE_COMBO              1116
#define IDC_ENCODE_CMDLINE_EDIT         1117
#define IDC_QUALITY_SLIDER              1119
#define IDC_BITRATE_COMBO               1120
#define IDC_ADD_BUTTON                  1121
#define IDC_VBR_QUALITY_COMBO           1121
#define IDC_TARGET_FILE_EXIST_COMBO     1122
#define IDC_DELETE_BUTTON               1123
#define IDC_CLEAR_BUTTON                1124
#define IDC_BACKGROUND_GAUSS_BLUR_CHECK 1124
#define IDC_LYRIC_BACKGROUND_CHECK      1125
#define IDC_SAVE_BUTTON                 1126
#define IDC_DARK_MODE_CHECK             1126
#define IDC_SHOW_DESKTOP_LYRIC          1126
#define IDC_AUTO_RUN_CHECK              1126
#define IDC_DISABLE_DELETE_FROM_DISK_CHECK 1126
#define IDC_FFMPEG_ENABLE_WASAPI        1126
#define IDC_OUTPUT_DEVICE_COMBO         1128
#define IDC_FORMAT_LIST                 1129
#define IDC_HOTKEY1                     1130
#define IDC_STATIC_COPYRIGHT            1131
#define IDC_MINIMIZE_TO_NOTIFY_RADIO    1132
#define IDC_EXIT_PROGRAM_RADIO          1133
#define IDC_USE_INNER_IMAGE_FIRST_CHECK 1133
#define IDC_LYRIC_COMPATIBLE_MODE       1134
#define IDC_UNASSOCIATE_LINK            1135
#define IDC_SHOW_DEFAULT_ALBUM_ICON_CHK 1135
#define IDC_DONATE_STATIC               1136
#define IDC_SEARCH_BOX_TRANSPARENT_IN_WHITE_MODE 1136
#define IDC_INPUT_EDIT                  1138
#define IDC_BASS_RADIO                  1139
#define IDC_TEXT_COLOR1_STATIC          1140
#define IDC_TEXT_COLOR2_STATIC          1142
#define IDC_TEXT_GRADIENT_COMBO         1143
#define IDC_HIGHLIGHT_COLOR1_STATIC     1144
#define IDC_HIGHLIGHT_COLOR2_STATIC     1145
#define IDC_LYRIC_OPACITY_STATIC        1146
#define IDC_LYRIC_OPACITY_SLIDER        1147
#define IDC_HIDE_LYRIC_WITHOUT_LYRIC_CHECK 1148
#define IDC_HIDE_LYRIC_PAUSE_CHECK      1149
#define IDC_TEST_TOOLBAR                1149
#define IDC_HIDE_LYRIC_WITHOUT_LYRIC_CHECK3 1150
#define IDC_PLAYLIST_TOOLBAR            1150
#define IDC_ENABLE_BACKGROUND_CHECK     1151
#define IDC_SHOW_UNLOCK_WHEN_LOCKED     1151
#define IDC_TEST_PROGRESS_BAR           1152
#define IDC_PROGRESS_TEXT               1153
#define IDC_PROGRESS_BAR                1154
#define IDC_MFCEDITBROWSE1              1155
#define IDC_FREQ_COMBO                  1156
#define IDC_CLASSIFY_LIST               1158
#define IDC_SONG_LIST                   1159
#define IDC_FOLDER_EXPLORE_TREE         1160
#define IDC_DIR_LIST                    1161
#define IDC_LOW_FREQ_IN_CENTER_CHECK    1162
#define IDC_ALIGNMENT_COMBO             1163
#define IDC_LYRIC_SAVE_COMBO            1164
#define IDC_USE_INNER_LYRIC_CHECK       1165
#define IDC_LYRIC_FILE_STATIC           1166
#define IDC_ALIGNMENT_COMBO2            1166
#define IDC_PLAYLIST_DISPLAY_MODE_OMBO  1167
#define IDC_DESKTOP_LYRIC_ALIGNMENT_COMBO 1167
#define IDC_RECENT_PLAYED_RANGE_OMBO    1168
#define IDC_DEFAULT_ALBUM_COVER_HQ      1168
#define IDC_UI_INTERVAL_EDIT            1169
#define IDC_SEARCH_RESULT_LIST          1170
#define IDC_DELETE_FILE_BUTTON          1171
#define IDC_LYRIC_NAME_EDIT             1172
#define IDC_PREVIEW_STATIC              1173
#define IDC_NOTIFY_ICON_AUTO_ADAPT_CHECK 1174
#define IDC_SHOW_PLAYLIST_TOOLTIP_CHECK 1174
#define IDC_LYRIC_HIDE_BLANK_LINE_CHECK 1174
#define IDC_FFMPEG_ENABLE_WASAPI_EXCLUSIVE 1174
#define IDC_BTN_ROUND_CORNERS_CHECK     1175
#define IDC_FLOAT_PLAYLIST_FOLLOW_MAIN_WND_CHECK 1175
#define IDC_SHOW_SONG_INFO_IF_LYRIC_NOT_EXIST_CHECK 1175
#define IDC_USE_MEDIA_TRANS_CONTORL_CHECK 1175
#define IDC_UI_STATIC                   1176
#define IDC_ALBUM_CHECK                 1177
#define IDC_GENRE_CHECK                 1178
#define IDC_YEAR_CHECK                  1179
#define IDC_FILE_TYPE_CHECK             1180
#define IDC_DEFAULT_BACKGROUND_PATH_EDIT 1182
#define IDC_INSERT_RADIO                1183
#define IDC_USE_DESKTOP_BACKGROUND_CHECK 1184
#define IDC_ID3V2_TYPE_COMBO            1185
#define IDC_GITHUB_RADIO                1186
#define IDC_GITEE_RADIO                 1187
#define IDC_ORIGINAL_STATIC             1187
#define IDC_SAVE_TO_APPDATA_RADIO       1188
#define IDC_SAVE_TO_PROGRAM_DIR_RADIO   1189
#define IDC_FFMPEG_RADIO                1190
#define IDC_FFMPEG_CACHE_LENGTH         1191
#define IDC_FFMPEG_MAX_RETRY_COUNT      1192
#define IDC_FFMPEG_URL_RETRY_INTERVAL   1193
#define IDC_FFMPEG_DOWN_SYSLINK         1194
#define IDC_SYSLINK_BASS                1195
#define IDC_SYSLINK_TAGLIB              1196
#define IDC_SYSLINK_TINYXML2            1197
#define IDC_SAVE_TO_SONG_FOLDER2        1197
#define IDC_SYSLINK_SCINTILLA           1198
#define IDC_ALBUM_COVER_PATH_EDIT       1198
#define IDC_SYSLINK_TRAFFICMONITOR      1199
#define IDC_SYSLINK_SIMPLENOTEPAD       1200
#define IDC_ALWAYS_SHOW_STATUSBAR_CHECK 1201
#define IDC_SHOW_SYSTEM_TITLEBAR_CHECK  1203
#define IDC_SHOW_SETTINGS_BTN_CHECK     1204
#define IDC_SHOW_SKIN_BTN_CHECK         1205
#define IDC_SHOW_MINI_MODE_BTN_CHECK    1206
#define IDC_SHOW_FULLSCREEN_BTN_CHECK   1207
#define IDC_SHOW_MINIMIZE_BTN_CHECK     1208
#define IDC_SHOW_MAXIMIZE_BTN_CHECK     1209
#define IDC_ENABLE_LASTFM               1210
#define IDC_SHOW_DARK_LIGHT_BTN_CHECK   1210
#define IDC_LASTFM_STATUS               1211
#define IDC_LASTFM_LEAST_DUR            1212
#define IDC_LASTFM_LEAST_PERDUR         1213
#define IDC_LASTFM_LOGIN                1214
#define IDC_LASTFM_AUTO_SCROBBLE        1215
#define IDC_LASTFM_AUTO_SCROBBLE_MIN    1216
#define IDC_LASTFM_CACHE_STATUS         1217
#define IDC_LASTFM_UPLOAD_CACHE         1218
#define IDC_LASTFM_ENABLE_HTTPS         1219
#define IDC_LASTFM_ENABLE_NOWPLAYING    1220
#define IDC_COMP_LEVEL_STATIC           1221
#define IDC_DOWNLOAD_OPTION_GROUPBOX    1221
#define IDC_COVER_LOCATION_STATIC       1222
#define IDC_REMOVE_FILE_NOT_EXIST_WHEN_UPDATE_CHECK 1223
#define IDC_FFMPEG_MAX_WAIT_TIME        1224
#define IDC_ACKNOWLEDGEMENT_SYSLINK     1225
#define IDC_HSPLITER_STATIC             1226
#define IDC_ARTIST_SPLIT_EXT_EDIT       1227
#define IDC_IGNORE_TOO_SHORT_CHECK      1228
#define IDC_STATIC_THIRD_PARTY_LIB      1229
#define IDC_STATIC_OTHER_SOFTWARE       1230
#define IDC_VISUAL_EFFECTS_STATIC       1231
#define IDC_TXT_SPECTRUM_HIGHT_STATIC   1232
#define IDC_TXT_COVER_FIT_STATIC        1233
#define IDC_TXT_TRANSPARENT_STATIC      1234
#define IDC_TXT_BG_SETTING_STATIC       1235
#define IDC_TXT_BG_TRANSPARENCY_STATIC  1236
#define IDC_TXT_GAUSS_BLUR_RADIUS_STATIC 1237
#define IDC_TXT_DEFAULT_BG_PATH_EDIT_STATIC 1238
#define IDC_TXT_COVER_OPT_STATIC        1239
#define IDC_TXT_EXT_COVER_FILE_NAME_STATIC 1240
#define IDC_TXT_EXT_COVER_FOLDER_STATIC 1241
#define IDC_TXT_THEME_COLOR_STATIC      1242
#define IDC_PRESET_COLOR_STATIC         1243
#define IDC_TXT_STATUS_BAR_STATIC       1244
#define IDC_TXT_TITLE_BAR_STATIC        1245
#define IDC_TXT_TITLE_BAR_BTN_SEL_STATIC 1246
#define IDC_NA_ICO_STATIC               1247
#define IDC_TXT_NA_ICO_SEL_STATIC       1248
#define IDC_TXT_ADV_STATIC              1249
#define IDC_TXT_UI_INTERVAL_STATIC      1250
#define IDC_TXT_CLEAN_UP_RANGE_SEL_STATIC 1251
#define IDC_TXT_COVER_DL_TITLE_STATIC   1252
#define IDC_TXT_COVER_DL_ARTIST_STATIC  1253
#define IDC_TXT_OPT_DATA_APP_SETTING_STATIC 1254
#define IDC_TXT_OPT_DATA_UPDATE_SOURCE_SEL_STATIC 1255
#define IDC_TXT_OPT_DATA_LANGUAGE_SEL_STATIC 1256
#define IDC_TXT_OPT_DATA_DATA_FILE_CFG_STATIC 1257
#define IDC_TXT_OPT_DATA_CLOSE_MAIN_WINDOW_STATIC 1258
#define IDC_TXT_OPT_DATA_DL_SETTING_STATIC 1259
#define IDC_TXT_OPT_DATA_AUTO_DL_LYRIC_SAVE_SEL_STATIC 1260
#define IDC_TXT_OPT_DATA_AUTO_DL_COVER_SAVE_SEL_STATIC 1261
#define IDC_TXT_OPT_DATA_MIDI_SETTING_STATIC 1262
#define IDC_TXT_OPT_DATA_MIDI_SF2_PATH_STATIC 1263
#define IDC_TXT_EQ_PRESET_STATIC        1264
#define IDC_TXT_EQ_CHANNEL_SETTING_STATIC 1265
#define IDC_TXT_FIND_KEY_WORD_INPUT_STATIC 1266
#define IDC_TXT_FIND_FIND_RANGE_STATIC  1267
#define IDC_TXT_FIND_OPT_STATIC         1268
#define IDC_TXT_ENCODE_OPT_FLAC_CMP_LEVEL_STATIC 1269
#define IDC_TXT_ENCODE_OPT_FLAC_CMP_LEVEL_LOW_STATIC 1270
#define IDC_TXT_ENCODE_OPT_FLAC_CMP_LEVEL_HIGH_STATIC 1271
#define IDC_TXT_FORMAT_CONVERT_OUT_FORMAT_SEL_STATIC 1272
#define IDC_TXT_FORMAT_CONVERT_FILE_LIST_STATIC 1273
#define IDC_TXT_FORMAT_CONVERT_OPT_STATIC 1274
#define IDC_TXT_FORMAT_CONVERT_OUT_FILE_NAME_STATIC 1275
#define IDC_TXT_FORMAT_CONVERT_FILE_EXIST_SEL_STATIC 1276
#define IDC_TXT_FORMAT_CONVERT_OUT_DIR_STATIC 1277
#define IDC_TXT_OPT_HOT_KEY_SHORTCUT_KEY_SEL_STATIC 1278
#define IDC_TXT_LYRIC_BDL_DL_OPT_STATIC 1279
#define IDC_TXT_LYRIC_BDL_SAVE_ENCODE_SEL_STATIC 1280
#define IDC_TXT_LYRIC_BDL_SAVE_DIR_SEL_STATIC 1281
#define IDC_TXT_LYRIC_BDL_SONG_LIST_STATIC 1282
#define IDC_TXT_LYRIC_DL_TITLE_STATIC   1283
#define IDC_TXT_LYRIC_DL_ARTIST_STATIC  1284
#define IDC_TXT_LYRIC_DL_OPT_STATIC     1285
#define IDC_TXT_LYRIC_DL_SAVE_ENCODE_SEL_STATIC 1286
#define IDC_TXT_LYRIC_DL_SAVE_DIR_SEL_STATIC 1287
#define IDC_TXT_LRC_RELATE_LRC_TITLE_STATIC 1288
#define IDC_TXT_LRC_RELATE_SEARCH_RESULT_STATIC 1289
#define IDC_TXT_OPT_LRC_OPT_STATIC      1290
#define IDC_TXT_OPT_LRC_LRC_FOLDER_STATIC 1291
#define IDC_TXT_OPT_LRC_SAVE_POLICY_SEL_STATIC 1292
#define IDC_TXT_OPT_LRC_WINDOW_LRC_STATIC 1293
#define IDC_TXT_OPT_LRC_WINDOW_LRC_LINE_SPACING_STATIC 1294
#define IDC_TXT_OPT_LRC_WINDOW_LRC_ALIGN_SEL_STATIC 1295
#define IDC_TXT_OPT_LRC_DESKTOP_LRC_STATIC 1296
#define IDC_TXT_OPT_LRC_DESKTOP_LRC_COLOR_TEXT_STATIC 1297
#define IDC_TXT_OPT_LRC_DESKTOP_LRC_COLOR_HIGHLIGHT_STATIC 1298
#define IDC_TXT_OPT_LRC_DESKTOP_LRC_TRANSPARENCY_STATIC 1299
#define IDC_TXT_OPT_LRC_DESKTOP_LRC_ALIGN_SEL_STATIC 1300
#define IDC_TXT_OPT_LRC_SEARCH_BOX_FUNCTION_STATIC 1301
#define IDC_TXT_OPT_LRC_SEARCH_BOX_BG_COLOR_SEL_STATIC 1302
#define IDC_TXT_OPT_LRC_SEARCH_BOX_ALIGN_SEL_STATIC 1303
#define IDC_TXT_OPT_MEDIA_LIB_MEDIA_LIB_OPT_STATIC 1304
#define IDC_TXT_OPT_MEDIA_LIB_TOO_SHORT_SEC_STATIC 1305
#define IDC_TXT_OPT_MEDIA_LIB_ARTIST_SPLIT_EXT_SEL_STATIC 1306
#define IDC_TXT_OPT_MEDIA_LIB_MEDIA_LIB_UPDATE_OPT_STATIC 1307
#define IDC_TXT_OPT_MEDIA_LIB_MEDIA_LIB_DIR_STATIC 1308
#define IDC_TXT_OPT_MEDIA_LIB_MEDIA_LIB_DISP_TAB_STATIC 1309
#define IDC_TXT_OPT_MEDIA_LIB_PLAYLIST_OPT_STATIC 1310
#define IDC_TXT_OPT_MEDIA_LIB_PLAYLIST_DISPLAY_MODE_STATIC 1311
#define IDC_TXT_OPT_MEDIA_LIB_PLAYLIST_ITEM_HEIGHT_STATIC 1312
#define IDC_TXT_OPT_MEDIA_LIB_RECENT_PLAY_STATIC 1313
#define IDC_TXT_OPT_MEDIA_LIB_RECENT_PLAY_RANGE_SEL_STATIC 1314
#define IDC_TXT_OPT_MEDIA_LIB_CLEAN_MEDIA_LIB_STATIC 1315
#define IDC_TXT_OPT_MEDIA_LIB_TAG_EDIT_STATIC 1316
#define IDC_TXT_OPT_MEDIA_LIB_TAG_ID3V2_WRITE_TYPE_STATIC 1317
#define IDC_TXT_OPT_LAST_FM_STATIC      1318
#define IDC_TXT_OPT_LAST_FM_AUTO_UPLOAD_THRESHOLD_STATIC 1319
#define IDC_TXT_OPT_LAST_FM_CACHE_CONDITION_STATIC 1320
#define IDC_TXT_OPT_LAST_FM_CACHE_CONDITION_PERCENT_STATIC 1321
#define IDC_TXT_OPT_LAST_FM_CACHE_CONDITION_DURATION_STATIC 1322
#define IDC_TXT_ENCODE_OPT_MP3_VBR_QUALITY_SEL_STATIC 1323
#define IDC_TXT_ENCODE_OPT_MP3_VBR_QUALITY_LOW_STATIC 1324
#define IDC_TXT_ENCODE_OPT_MP3_VBR_QUALITY_HIGH_STATIC 1325
#define IDC_TXT_ENCODE_OPT_OGG_ENCODE_QUALITY_SEL_STATIC 1326
#define IDC_TXT_ENCODE_OPT_OGG_ENCODE_QUALITY_LOW_STATIC 1327
#define IDC_TXT_ENCODE_OPT_OGG_ENCODE_QUALITY_HIGH_STATIC 1328
#define IDC_TXT_OPT_PLAY_PLAY_OPT_STATIC 1329
#define IDC_TXT_OPT_PLAY_CORE_STATIC    1330
#define IDC_TXT_OPT_PLAY_DEVICE_STATIC  1331
#define IDC_TXT_OPT_PLAY_DEVICE_SEL_STATIC 1332
#define IDC_TXT_OPT_PLAY_FFMPEG_CORE_SETTING_STATIC 1333
#define IDC_TXT_OPT_PLAY_FFMPEG_CORE_CACHE_LENGTH_STATIC 1334
#define IDC_TXT_OPT_PLAY_FFMPEG_CORE_MAX_RETRY_COUNT_STATIC 1335
#define IDC_TXT_OPT_PLAY_FFMPEG_CORE_URL_RETRY_INTERVAL_STATIC 1336
#define IDC_TXT_OPT_PLAY_FFMPEG_CORE_MAX_WAIT_TIME_STATIC 1337
#define IDC_TXT_PROPERTY_DLG_FILE_INFO_STATIC 1338
#define IDC_TXT_PROPERTY_DLG_FILE_NAME_STATIC 1339
#define IDC_TXT_PROPERTY_DLG_FILE_PATH_STATIC 1340
#define IDC_TXT_PROPERTY_DLG_FILE_TYPE_STATIC 1341
#define IDC_TXT_PROPERTY_DLG_FILE_DURATION_STATIC 1342
#define IDC_TXT_PROPERTY_DLG_FILE_SIZE_STATIC 1343
#define IDC_TXT_PROPERTY_DLG_FILE_BIT_RATE_STATIC 1344
#define IDC_TXT_PROPERTY_DLG_FILE_CHANNELS_STATIC 1345
#define IDC_TXT_PROPERTY_DLG_FILE_FREQ_STATIC 1346
#define IDC_TXT_PROPERTY_DLG_FILE_BIT_DEPTH_STATIC 1347
#define IDC_TXT_PROPERTY_DLG_TAG_INFO_STATIC 1348
#define IDC_TXT_PROPERTY_DLG_TAG_TITLE_STATIC 1349
#define IDC_TXT_PROPERTY_DLG_TAG_ARTIST_STATIC 1350
#define IDC_TXT_PROPERTY_DLG_TAG_ALBUM_STATIC 1351
#define IDC_TXT_PROPERTY_DLG_TAG_TRACK_STATIC 1352
#define IDC_TXT_PROPERTY_DLG_TAG_YEAR_STATIC 1353
#define IDC_TXT_PROPERTY_DLG_TAG_GENRE_STATIC 1354
#define IDC_TXT_PROPERTY_DLG_TAG_COMMENT_STATIC 1355
#define IDC_TXT_REVERB_STRENGTH_STATIC  1356
#define IDC_TXT_REVERB_TIME_STATIC      1357
#define IDC_TXT_LIB_PATH_CURRENT_FOLDER_STATIC 1358
#define IDC_TXT_TAG_EDIT_PATH_STATIC    1359
#define IDC_TXT_TAG_SEL_CLICK_BTN_SEL_STATIC 1360
#define IDC_FLOAT_PLAYLIST_BY_DEFAULT_CHECK 1361
#define IDC_LYRIC_AND_TRANSLATION_IN_SAME_LINE_RADIO 1362
#define IDC_DOWN_LOAD_LYRIC_TRANSLATION_FORMAT_STATIC 1363
#define IDC_LYRIC_AND_TRANSLATION_IN_DIFFERENT_LINE_RADIO 1364
#define IDC_SORT_BUTTON                 1365
#define IDC_USE_SYSTEM_TITLEBAR_RADIO   1366
#define IDC_USE_OWNER_DRAW_TITLEBAR_RADIO 1367
#define IDC_MIDI_USE_INNER_LYRIC_CHECK  1368
#define IDC_TXT_OPERATION_SETTINGS_STATIC 1369
#define IDC_GLOBAL_MOUSE_WHEEL_VOLUME_ADJUSTMENT_CHECK 1370
#define IDC_UI_SEARCH_BOX_EDIT          1371
#define ID_FILE_OPEN_FOLDER             32774
#define ID_PLAY_PAUSE                   32778
#define ID_STOP                         32779
#define ID_PREVIOUS                     32781
#define ID_NEXT                         32783
#define ID_REW                          32787
#define ID_FF                           32788
#define ID_PLAY                         32789
#define ID_PAUSE                        32790
#define ID_MEDIA_LIB                    32793
#define ID_FIND                         32794
#define ID_EXPLORE_PATH                 32795
#define ID_PLAY_ORDER                   32804
#define ID_PLAY_SHUFFLE                 32805
#define ID_PLAY_RANDOM                  32806
#define ID_LOOP_PLAYLIST                32807
#define ID_LOOP_TRACK                   32808
#define ID_PLAY_TRACK                   32809
#define ID_OPTION_SETTINGS              32825
#define ID_RELOAD_PLAYLIST              32827
#define ID_PLAY_ITEM                    32830
#define ID_TEST                         32831
#define ID_ITEM_PROPERTY                32833
#define ID_TEST_DIALOG                  32834
#define ID_REMOVE_FROM_PLAYLIST         32835
#define ID_EXPLORE_TRACK                32840
#define ID_RE_INI_BASS                  32843
#define ID_SORT_BY_FILE                 32850
#define ID_SORT_BY_PATH                 32851
#define ID_SORT_BY_TITLE                32852
#define ID_SORT_BY_ARTIST               32853
#define ID_SORT_BY_ALBUM                32854
#define ID_SORT_BY_TRACK                32855
#define ID_SORT_BY_LISTEN_TIME          32856
#define ID_SORT_BY_MODIFIED_TIME        32857
#define ID_DELETE_FROM_DISK             32861
#define ID_DISP_FILE_NAME               32862
#define ID_DISP_TITLE                   32863
#define ID_DISP_ARTIST_TITLE            32864
#define ID_DISP_TITLE_ARTIST            32865
#define ID_MINI_MODE_EXIT               32870
#define ID_SONG_INFO                    32871
#define ID_MINI_MODE                    32872
#define ID_RELOAD_LYRIC                 32876
#define ID_COPY_CURRENT_LYRIC           32880
#define ID_COPY_ALL_LYRIC               32881
#define ID_LYRIC_FORWARD                32885
#define ID_LYRIC_DELAY                  32886
#define ID_SAVE_MODIFIED_LYRIC          32888
#define ID_EDIT_LYRIC                   32890
#define ID_DOWNLOAD_LYRIC               32892
#define ID_LYRIC_BATCH_DOWNLOAD         32894
#define ID_DELETE_LYRIC                 32897
#define ID_DARK_MODE                    32900
#define ID_LYRIC_OPEN                   32911
#define ID_LYRIC_SAVE_AS                32913
#define ID_LYRIC_FIND                   32924
#define ID_LYRIC_REPLACE                32925
#define ID_LYRIC_SAVE                   32927
#define ID_FIND_NEXT                    32929
#define ID_EQUALIZER                    32931
#define ID_EXPLORE_ONLINE               32933
#define ID_LD_LYRIC_DOWNLOAD            32937
#define ID_LD_LYRIC_SAVEAS              32938
#define ID_LD_COPY_TITLE                32944
#define ID_LD_COPY_ALBUM                32945
#define ID_LD_COPY_ID                   32946
#define ID_LD_VIEW_ONLINE               32947
#define ID_LD_COPY_ARTIST               32948
#define ID_BROWSE_LYRIC                 32955
#define ID_TRANSLATE_TO_SIMPLIFIED_CHINESE 32957
#define ID_TRANSLATE_TO_TRANDITIONAL_CHINESE 32959
#define ID_LE_TRANSLATE_TO_SIMPLIFIED_CHINESE 32960
#define ID_LE_TRANSLATE_TO_TRANDITIONAL_CHINESE 32961
#define ID_ALBUM_COVER_SAVE_AS          32962
#define ID_LYRIC_INSERT_TAG             32963
#define ID_LYRIC_REPLACE_TAG            32964
#define ID_LYRIC_DELETE_TAG             32965
#define ID_PLAY_PATH                    32968
#define ID_DELETE_PATH                  32970
#define ID_BROWSE_PATH                  32972
#define ID_CLEAR_INVALID_PATH           32974
#define ID_DOWNLOAD_ALBUM_COVER         32975
#define ID_CURRENT_EXPLORE_ONLINE       32977
#define ID_DELETE_ALBUM_COVER           32979
#define ID_COPY_FILE_TO                 32982
#define ID_MOVE_FILE_TO                 32983
#define ID_FORMAT_CONVERT               32984
#define ID_FORMAT_CONVERT1              32986
#define ID_ADD_FILE                     32988
#define ID_DELETE_SELECT                32990
#define ID_CLEAR_LIST                   32991
#define ID_MOVE_UP                      32992
#define ID_MOVE_DOWN                    32993
#define ID_EDIT_TAG_INFO                32995
#define ID_SUPPORTED_FORMAT             32998
#define ID_VOLUME_UP                    33000
#define ID_VOLUME_DOWN                  33001
#define ID_SHOW_PLAY_LIST               33002
#define ID_MENU_EXIT                    33003
#define ID_MINIMODE_RESTORE             33005
#define ID_MINI_MIDE_MINIMIZE           33008
#define ID_SHOW_PLAYLIST                33010
#define ID_SHOW_MENU_BAR                33012
#define ID_FULL_SCREEN                  33014
#define ID_CREATE_PLAY_SHORTCUT         33016
#define ID_LISTEN_STATISTICS            33018
#define ID_LD_PREVIEW                   33020
#define ID_ALWAYS_ON_TOP                33023
#define ID_FLOAT_PLAYLIST               33026
#define ID_DOCKED_PLAYLIST              33029
#define ID_FLOATED_PLAYLIST             33030
#define ID_PLAYLIST_ADD_FILE            33036
#define ID_EMPTY_PLAYLIST               33037
#define ID_PLAY_PLAYLIST                33041
#define ID_RENAME_PLAYLIST              33042
#define ID_DELETE_PLAYLIST              33043
#define ID_MOVE_PLAYLIST_ITEM_UP        33045
#define ID_MOVE_PLAYLIST_ITEM_DOWN      33046
#define ID_REMOVE_SAME_SONGS            33048
#define ID_ADD_TO_NEW_PLAYLIST          33050
#define ID_ADD_TO_DEFAULT_PLAYLIST      33051
#define ID_ADD_TO_MY_FAVOURITE          33052
#define ID_TOOL_FILE_RELATE             33096
#define ID_ADD_TO_OTHER_PLAYLIST        33097
#define ID_PLAYLIST_ADD_FOLDER          33102
#define ID_ADD_REMOVE_FROM_FAVOURITE    33103
#define ID_REMOVE_INVALID_ITEMS         33105
#define ID_NEW_PLAYLIST                 33107
#define ID_FILE_OPEN_URL                33109
#define ID_PLAYLIST_ADD_URL             33111
#define ID_LYRIC_DISPLAYED_DOUBLE_LINE  33113
#define ID_LOCK_DESKTOP_LRYIC           33114
#define ID_CLOSE_DESKTOP_LYRIC          33116
#define ID_LYRIC_DEFAULT_STYLE1         33121
#define ID_LYRIC_DEFAULT_STYLE2         33122
#define ID_LYRIC_DEFAULT_STYLE3         33123
#define ID_LYRIC_BACKGROUND_PENETRATE   33126
#define ID_PLAYLIST_SELECT_ALL          33127
#define ID_PLAYLIST_SELECT_NONE         33128
#define ID_PLAYLIST_SELECT_REVERT       33129
#define ID_LYRIC_DEFAULT_STYLE1_MODIFY  33132
#define ID_LYRIC_DEFAULT_STYLE2_MODIFY  33133
#define ID_LYRIC_DEFAULT_STYLE3_MODIFY  33134
#define ID_RESTORE_DEFAULT_STYLE        33136
#define ID_ONLINE_HELP                  33138
#define ID_SPEED_UP                     33142
#define ID_SLOW_DOWN                    33143
#define ID_ORIGINAL_SPEED               33144
#define ID_ADD_TO_NEW_PLAYLIST_AND_PLAY 33145
#define ID_PLAY_ITEM_IN_FOLDER_MODE     33147
#define ID_COPY_TEXT                    33148
#define ID_ALWAYS_SHOW_STATUS_BAR       33149
#define ID_SHOW_MAIN_WINDOW             33150
#define ID_AB_REPEAT                    33151
#define ID_SET_A_POINT                  33153
#define ID_SET_B_POINT                  33154
#define ID_RESET_AB_REPEAT              33155
#define ID_NEXT_AB_REPEAT               33157
#define ID_SAVE_CURRENT_PLAYLIST_AS     33158
#define ID_FILE_OPEN_PLAYLIST           33160
#define ID_SAVE_AS_NEW_PLAYLIST         33164
#define ID_CREATE_DESKTOP_SHORTCUT      33165
#define ID_CREATE_MINI_MODE_SHORT_CUT   33166
#define ID_REMOVE_CURRENT_FROM_PLAYLIST 33167
#define ID_DELETE_CURRENT_FROM_DISK     33168
#define ID_MINI_MODE_ALWAYS_ON_TOP      33170
#define ID_ALWAYS_USE_EXTERNAL_ALBUM_COVER 33171
#define ID_LRYIC_MERGE_SAME_TIME_TAG    33174
#define ID_LYRIC_SWAP_TEXT_AND_TRANSLATION 33175
#define ID_LYRIC_TIME_TAG_FORWARD       33177
#define ID_LYRIC_TIME_TAG_DELAY         33179
#define ID_RELATE_LOCAL_LYRIC           33181
#define ID_ALBUM_COVER_INFO             33183
#define ID_UNLINK_LYRIC                 33184
#define ID_SHOW_DESKTOP_LYRIC           33185
#define ID_CONTAIN_SUB_FOLDER           33188
#define ID_HELP_UPDATE_LOG              33196
#define ID_LD_RELATE                    33197
#define ID_COVER_BROWSE                 33198
#define ID_COVER_DELETE                 33199
#define ID_COVER_SAVE_AS                33201
#define ID_RENAME                       33204
#define ID_EMBED_LYRIC_TO_AUDIO_FILE    33208
#define ID_DELETE_LYRIC_FROM_AUDIO_FILE 33209
#define ID_SWITCH_UI                    33210
#define ID_SWITCH_UI_1                  33211
#define ID_SWITCH_UI_2                  33212
#define ID_SWITCH_UI_3                  33213
#define ID_SWITCH_UI_4                  33214
#define ID_SWITCH_UI_5                  33215
#define ID_SWITCH_UI_6                  33216
#define ID_SWITCH_UI_7                  33217
#define ID_SWITCH_UI_8                  33218
#define ID_SWITCH_UI_9                  33219
#define ID_SWITCH_UI_10                 33220
#define ID_SHOW_LYRIC_TRANSLATE         33320
#define ID_COPY_ALL_TEXT                33321
#define ID_VIEW_ARTIST                  33322
#define ID_LOCATE_TO_CURRENT            33323
#define ID_VIEW_ALBUM                   33324
#define ID_RATING_1                     33332
#define ID_RATING_2                     33333
#define ID_RATING_3                     33334
#define ID_RATING_4                     33335
#define ID_RATING_5                     33336
#define ID_RATING_NONE                  33337
#define ID_USE_STANDARD_TITLE_BAR       33339
#define ID_PLAYLIST_VIEW_ARTIST         33340
#define ID_PLAYLIST_VIEW_ALBUM          33341
#define ID_PLAYLIST_SELECT_CHANGE       33342
#define ID_PLAYLIST_OPTIONS             33343
#define ID_RECENT_FOLDER_PLAYLIST_MENU_START 33344
#define ID_RECENT_FOLDER_PLAYLIST_MENU_END 33384
#define ID_HELP_CUSTOM_UI               33386
#define ID_COMPRESS_SIZE                33387
#define ID_PLAYLIST_SAVE_AS             33389
#define ID_HELP_FAQ                     33390
#define ID_SEEK_TO_CUR_LINE             33392
#define ID_REPEAT_MODE                  33393
#define ID_PLAY_AS_NEXT                 33394
#define ID_MINIMODE_UI_DEFAULT          33396
#define ID_MINIMODE_UI_MAX              33460
#define ID_PLAYLIST_FIX_PATH_ERROR      33461
#define ID_PLAYLIST_BROWSE_FILE         33463
#define ID_LYRIC_AND_TRANSLATION_IN_SAME_LINE 33464
#define ID_LYRIC_AND_TRANSLATION_IN_DIFFERENT_LINE 33465
#define ID_MORE_RECENT_ITEMS            33466
#define ID_VIEW_IN_MEDIA_LIB            33467
#define ID_RECENT_PLAYED_REMOVE         33468
#define ID_LIB_PLAYLIST_SORT_RECENT_PLAYED 33469
#define ID_LIB_PLAYLIST_SORT_RECENT_CREATED 33470
#define ID_LIB_PLAYLIST_SORT_NAME       33471
#define ID_LIB_FOLDER_SORT_RECENT_PLAYED 33472
#define ID_LIB_FOLDER_SORT_RECENT_ADDED 33473
#define ID_LIB_FOLDER_SORT_PATH         33474
#define ID_LIB_PLAYLIST_PROPERTIES      33475
#define ID_LIB_FOLDER_PROPERTIES        33476
#define ID_LIB_RECENT_PLAYED_ITEM_PROPERTIES 33477

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        628
#define _APS_NEXT_COMMAND_VALUE         33478
#define _APS_NEXT_CONTROL_VALUE         1372
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
