//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MusicPlayer2.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MUSICPLAYER2_DIALOG         102
#define IDS_STRING102                   102
#define IDS_HELP_INFO                   103
#define IDS_STRING103                   103
#define IDS_LYRIC_FOLDER_NOT_EXIST      104
#define IDS_BASS_VERSION_WARNING        105
#define IDS_CHECK_UPDATA_FAILED         106
#define IDS_CHECK_UPDATA_ERROR          107
#define IDS_UPDATE_AVLIABLE             108
#define IDS_UPDATE_AVLIABLE2            109
#define IDS_ALREADY_UPDATED             110
#define IDS_RESTART_EXIT                111
#define IDS_SERIALIZE_ERROR             112
#define IDS_SEND_EMAIL_TO_ATHOUR        113
#define IDS_GOTO_GITHUB                 114
#define IDS_DONATE_ATHOUR               115
#define IDS_LANGUAGE_CODE               116
#define IDS_DEFAULT_FONT                117
#define IDS_PLAY                        118
#define IDS_PAUSE                       119
#define IDS_PREVIOUS                    120
#define IDS_NEXT                        121
#define IDS_PLAY2                       122
#define IDS_PAUSE2                      123
#define IDS_CREATE_SHORTCUT_INFO        124
#define IDS_SHORTCUT_CREATED            125
#define IDS_SHORTCUT_CREAT_FAILED       126
#define IDS_MINI_MODE                   127
#define IDR_MAINFRAME                   128
#define IDS_MINI_MODE2                  128
#define IDS_SELECT_RENENT_FOLDER        129
#define IDR_MENU1                       130
#define IDS_PLAY_TIME                   130
#define IDS_CLEAR_SEARCH_RESULT         131
#define IDS_INPUT_KEY_WORD              132
#define IDD_SET_PATH_DIALOG             133
#define IDS_SEARCH_HERE                 133
#define IDS_NOW_PLAYING                 134
#define IDS_CONNOT_FIND_FILE            135
#define IDD_DIALOG1                     136
#define IDD_FIND_DIALOG                 136
#define IDS_ALL_SUPPORTED_FORMAT        136
#define IDS_ALL_FILES                   137
#define IDD_OPTIONS_DIALOG              138
#define IDS_OPEN_FOLDER_INFO            138
#define IDS_DELETE_FILE_INQUARY         139
#define IDD_LYRIC_SETTING_DIALOG        140
#define IDS_CONNOT_DELETE_FILE          140
#define IDS_COPY_CLIPBOARD_FAILED       141
#define IDD_DIALOG2                     142
#define IDD_APPEREANCE_SETTING_DLG      142
#define IDS_ALL_LRYIC_COPIED            142
#define IDS_DEBUG_MODE                  143
#define IDR_POPUP_MENU                  144
#define IDS_NO_MIDI_SF2_WARNING         144
#define IDD_PROPERTY_DIALOG             145
#define IDS_SELECT_COPY_TARGET_FOLDER   145
#define IDS_SELECT_MOVE_TARGET_FOLDER   146
#define IDS_DEFAULT_TITLE               147
#define IDS_DEFAULT_ARTIST              148
#define IDS_DEFAULT_ALBUM               149
#define IDS_DEFAULT_YEAR                150
#define IDI_PREVIOUS                    151
#define IDS_DEFAULT_GENRE               151
#define IDI_PLAY_PAUSE                  152
#define IDS_DEFAULT_LYRIC_TEXT          152
#define IDS_DEFAULT_LYRIC_TEXT_CORTANA  153
#define IDI_NEXT1                       154
#define IDS_VOLUME                      154
#define IDI_PLAY                        155
#define IDS_PLAY_ERROR                  155
#define IDI_ICON2                       156
#define IDI_PAUSE                       156
#define IDS_SEEK_TO_MINUTE_SECOND       156
#define IDS_SHOW_HIDE_PLAYLIST          157
#define IDI_ICON1                       158
#define IDI_STOP                        158
#define IDS_BACK_TO_NARMAL              158
#define IDD_MESSAGE_DIALOG              159
#define IDS_EXIT_PROGRAM                159
#define IDS_SEEK_TO                     160
#define IDS_TITLE                       161
#define IDS_RHYTHM                      162
#define IDR_TEXT1                       163
#define IDS_SOUND_FONT                  163
#define IDD_MINI_DIALOG                 164
#define IDS_ARTIST                      164
#define IDS_ALBUM                       165
#define IDS_FORMAT                      166
#define IDR_MINI_MODE_MENU              167
#define IDS_MONO                        167
#define IDS_STEREO                      168
#define IDS_CHANNEL                     169
#define IDR_LYRIC_POPUP_MENU            170
#define IDS_NO_LYRIC_INFO               170
#define IDD_LYRIC_EDIT_DIALOG           171
#define IDS_LYRIC_SHOW                  171
#define IDS_TRAS                        172
#define IDD_DATA_SETTINGS_DIALOG        173
#define IDS_ALBUM_COVER                 173
#define IDS_INNER_ALBUM_COVER_TIP_INFO  174
#define IDS_OUT_IMAGE                   175
#define IDD_LYRIC_DOWNLOAD_DIALOG       176
#define IDS_PLAYLIST_INIT_INFO          176
#define IDS_REPEAT_MODE                 177
#define IDD_LYRIC_BATCH_DOWN_DIALOG     178
#define IDS_PLAY_ODER                   178
#define IDS_LOOP_PLAYLIST               179
#define IDR_LYRIC_EDIT_MENU             180
#define IDS_LOOP_TRACK                  180
#define IDD_EQUALIZER_DIALOG            181
#define IDS_PLAY_SHUFFLE                181
#define IDS_SHOW_LYRIC_TRANSLATION      182
#define IDD_SOUND_EFFECT_DIALOG         183
#define IDS_MOUSE_WHEEL_ADJUST_VOLUME   183
#define IDS_SWITCH_UI                   184
#define IDD_REVERB_DIALOG               185
#define IDS_SOUND_EFFECT_SETTING        185
#define IDS_SETTINGS                    186
#define IDR_LYRIC_DOWNLOAD_MENU         187
#define IDS_FIND_DLG_INFO               187
#define IDR_FIND_POPUP_MENU             188
#define IDS_FIND_RESULT                 188
#define IDR_MAIN_POPUP_MENU             189
#define IDS_NO_RESULT                   189
#define IDB_DEFAULT_COVER               190
#define IDS_NUMBER                      190
#define IDB_CORTANA_BLACK               191
#define IDS_FILE_NAME                   191
#define IDB_BITMAP2                     192
#define IDB_CORTANA_WHITE               192
#define IDS_FILE_PATH                   192
#define IDR_LYRIC_EDIT_TOOLBAR          193
#define IDS_CHARACTER_TOTAL             193
#define IDS_MODIFIED                    194
#define IDI_ADD_TAG                     195
#define IDS_UNMODIFIED                  195
#define IDI_REPLACE_TAG                 196
#define IDS_ENCODE_FORMAT               196
#define IDI_DELETE_TAG                  197
#define IDS_UTF8_NO_BOM                 197
#define IDI_SAVE                        198
#define IDS_LYRIC_SAVE_INRUARY          198
#define IDI_FIND                        199
#define IDS_LYRIC_FILE_FILTER           199
#define IDI_ICON4                       200
#define IDI_REPLACE                     200
#define IDS_SAVE_AS_ANSI                200
#define IDI_FF                          201
#define IDS_SAVE_AS_UTF8                201
#define IDI_REW                         202
#define IDS_REPLACE_COMPLETE_INFO       202
#define IDR_SET_PATH_POPUP_MENU         203
#define IDS_CONNOT_FIND_STRING          203
#define IDS_INSERT_TIME_TAG_TIP         204
#define IDS_REPLACE_TIME_TAG_TIP        205
#define IDD_DIALOG3                     206
#define IDD_COVER_DOWNLOAD_DIALOG       206
#define IDS_DELETE_TIME_TAG_TIP         206
#define IDS_SAVE_TIP                    207
#define IDD_FORMAT_CONVERT_DIALOG       208
#define IDS_PLAY_PAUSE_TIP              208
#define IDS_REWIND_TIP                  209
#define IDD_DIALOG4                     210
#define IDD_MP3_ENCODE_CFG_DIALOG       210
#define IDS_FAST_FOWARD_TIP             210
#define IDS_FIND_TIP                    211
#define IDD_OGG_ENCODE_CFG_DIALOG       212
#define IDS_REPLACE_TIP                 212
#define IDS_CANNOT_GET_SONG_LENGTH      213
#define IDD_WMA_ENCODE_CFG_DIALOG       214
#define IDS_NO_MATCHED_LYRIC            214
#define IDS_MP3_TAG_TYPE                215
#define IDR_FORMAT_CONVERT_POPUP_MENU   216
#define IDS_UNKNOW                      216
#define IDD_TAG_EDIT_DIALOG             217
#define IDS_CANNOT_WRITE_TO_FILE        217
#define IDS_FOLDER                      218
#define IDD_RECORDER_DIALOG             219
#define IDS_PATH                        219
#define IDS_TRACK_PLAYED                220
#define IDD_PLAY_SETTING_DIALOG         221
#define IDS_TRACK_TOTAL_NUM             221
#define IDD_SUPPORT_FORMAT_DIALOG       222
#define IDS_TOTAL_LENGTH                222
#define IDS_CLEAR_PATH_INQUARY          223
#define IDI_ICON3                       224
#define IDI_DEFAULT_COVER               224
#define IDS_PATH_CLEAR_COMPLETE         224
#define IDI_SKIN                        225
#define IDS_NONE                        225
#define IDI_EQ                          226
#define IDS_CLASSICAL                   226
#define IDI_SETTING                     227
#define IDS_POP                         227
#define IDI_LOOP_TRACK                  228
#define IDS_JAZZ                        228
#define IDI_LOOP_PLAYLIST               229
#define IDS_ROCK                        229
#define IDI_PLAY_ORDER                  230
#define IDS_SOFT                        230
#define IDI_PLAY_SHUFFLE                231
#define IDS_BASS                        231
#define IDI_SKIN_D                      232
#define IDS_ELIMINATE_BASS              232
#define IDI_EQ_D                        233
#define IDS_WEAKENING_TREBLE            233
#define IDI_SETTING_D                   234
#define IDS_USER_DEFINE                 234
#define IDI_LOOP_TRACK_D                235
#define IDS_EQUALIZER                   235
#define IDI_LOOP_PLAYLIST_D             236
#define IDS_REVERB                      236
#define IDI_PLAY_ORDER_D                237
#define IDS_PLUGIN_FILE_NAME            237
#define IDI_ICON6                       238
#define IDI_PLAY_SHUFFLE_D              238
#define IDS_FORMAT_SUPPORTED            238
#define IDI_MINI                        239
#define IDS_FILE_EXTENSION              239
#define IDI_ICON7                       240
#define IDI_MINI_D                      240
#define IDS_STATE                       240
#define IDD_HOT_KEY_SETTINGS_DIALOG     241
#define IDS_LYRIC_BATCH_DOWNLOADING_INFO 241
#define IDS_DOWNLOADING                 242
#define IDS_SKIPED                      243
#define IDR_MENU2                       243
#define IDR_NOTIFY_MENU                 243
#define IDS_NETWORK_CONNECTION_FAILED   244
#define IDI_SONG_INFO                   244
#define IDS_CANNOT_FIND_THIS_SONG       245
#define IDI_ICON8                       245
#define IDI_SONG_INFO_D                 245
#define IDS_LYRIC_DOWNLOAD_FAILED       246
#define IDI_SELECT_FOLDER               246
#define IDS_SONG_NO_LYRIC               247
#define IDI_SELECT_FOLDER_D             247
#define IDS_DOWNLOAD_ENCODE_WARNING     248
#define IDI_PLAYLIST                    248
#define IDS_SUCCESSED                   249
#define IDI_PLAYLIST_D                  249
#define IDS_DOWNLOAD_COMPLETE           250
#define IDS_RETURN_VALUE_OF_WAIT_FOR_SINGLE_OBJECT 251
#define IDS_SEARCHING                   252
#define IDS_SEARCH_FAILED_INFO          253
#define IDS_SEARCH_TIME_OUT             254
#define IDS_SEARCH_NO_SONG              255
#define IDS_SEARCH_NO_MATCHED           256
#define IDS_SEARCH_RELATED              257
#define IDS_SEARCH_BEST_MATCHED         258
#define IDS_LYRIC_OVERWRITE_INQUARY     259
#define IDS_DOWNLOAD_COMPLETE_SAVED     260
#define IDS_CONVERTING_STATE            261
#define IDS_MP3_LAME_ENCODER            262
#define IDS_AUTO_RENAME                 263
#define IDS_IGNORE                      264
#define IDS_OVERWRITE                   265
#define IDS_CONVERT_WMA_ERROR           266
#define IDS_NO_WMP9_OR_LATER            267
#define IDS_NO_SUPPORTED_ENCODER_WARNING 268
#define IDS_UNKNOW_ERROR                269
#define IDS_BASS_ENCODER_LOAD_ERROR     270
#define IDS_SET_OUTPUT_DIR_INFO         271
#define IDS_OUTPUT_DIR_NOT_EXIST        272
#define IDS_SELECT_OUTPUT_FOLDER        273
#define IDS_ERROR                       274
#define IDS_COMPLEATE                   275
#define IDS_SKIPED1                     276
#define IDS_CURRENT_SELECTED            277
#define IDS_CURRENT_COLOR               278
#define IDS_LIGNT_BLUE                  279
#define IDS_GREEN                       280
#define IDS_ORANGE                      281
#define IDS_CYAN_GREEN                  282
#define IDS_PINK                        283
#define IDS_LIGHT_PURPLE                284
#define IDS_STRETCH                     285
#define IDS_FILL                        286
#define IDS_ADAPT                       287
#define IDS_COVER_FIT_TIP_INFO          288
#define IDS_USE_OUT_IMAGE_TIP_INFO      289
#define IDS_DEFAULT_COVER_NAME_TIP_INFO 290
#define IDS_WHITE_THEME_COLOR_WARNING   291
#define IDS_FOLLOWING_SYSTEM            292
#define IDS_CLEAR_DATA_FILE_TIP_INFO    293
#define IDS_AUTO_DOWNLOAD_LYRIC_TIP_INFO 294
#define IDS_MIDI_INNER_LYRIC_TIP_INFO   295
#define IDS_CURRENT_DATA_FILE_SIZE      296
#define IDS_BYTE                        297
#define IDS_CLEAR_COMPLETE_INFO         298
#define IDS_SOUND_FONT_FILTER           299
#define IDS_FUNCTION                    300
#define IDS_SHORTCUT_KEY                301
#define IDS_PLAY_PAUSE                  302
#define IDS_STOP                        303
#define IDS_FAST_FORWARD                304
#define IDS_REWIND                      305
#define IDS_VOLUME_UP                   306
#define IDS_VOLUME_DOWN                 307
#define IDS_EXIT                        308
#define IDS_GLOBLE_HOT_KEY_WARNING      309
#define IDS_LYRIC_FUZZY_MATHC_TIP_INFO  310
#define IDS_LYRIC_PATH_TIP_INFO         311
#define IDS_CORTANA_SHOW_LYRIC_TIP_INFO 312
#define IDS_BLACK                       313
#define IDS_WHITE                       314
#define IDS_SELECT_LYRIC_FOLDER         315
#define IDS_LYRIC_SETTINGS              316
#define IDS_APPEARANCE_SETTINGS         317
#define IDS_GENERAL_SETTINGS            318
#define IDS_PLAY_SETTINGS               319
#define IDS_GLOBLE_HOTKEY               320
#define IDS_DEVICE_TYPE_DIGITAL         321
#define IDS_DEVICE_TYPE_DISPLAYPORT     322
#define IDS_DEVICE_TYPE_HANDSET         323
#define IDS_DEVICE_TYPE_HDMI            324
#define IDS_DEVICE_TYPE_HEADPHONES      325
#define IDS_DEVICE_TYPE_HEADSET         326
#define IDS_DEVICE_TYPE_LINE            327
#define IDS_DEVICE_TYPE_MICROPHONE      328
#define IDS_DEVICE_TYPE_NETWORK         329
#define IDS_DEVICE_TYPE_SPDIF           330
#define IDS_DEVICE_TYPE_SPEAKERS        331
#define IDS_ITEM                        332
#define IDS_VLAUE                       333
#define IDS_NAME                        334
#define IDS_DRIVER                      335
#define IDS_DEVICE_TYPE                 336
#define IDS_ALBUM_COVER_DOWNLOAD_FAILED_WARNING 337
#define IDS_AUDIO_FILE                  338
#define IDS_MINI_SEQUENCE               339
#define IDS_DELETE                      340
#define IDS_COPY                        341
#define IDS_MOVE                        342
#define IDS_INVALID_DIR_WARNING         343
#define IDS_DEFAULT_OUTPUT_DEVICE       344
#define IDS_BASIC_AUDIO_FORMAT          345
#define IDS_SOUND_FONT_LOAD_FAILED      346
#define IDS_LOAD_FAILED                 347
#define IDS_BASS_ERROR_LOG_INFO         348
#define IDS_LANGUAGE_CHANGE_INFO        349
#define IDS_STOPED                      350
#define IDS_PAUSED                      351
#define IDS_RECENT_PATH_SERIALIZE_ERROR_LOG 352
#define IDS_NO_RESULT_TO_SHOW           353
#define IDS_BITRATE                     354
#define IDS_TRACK                       355
#define IDS_STRING356                   356
#define IDS_LENGTH                      356
#define IDS_CLOSE_BTN                   357
#define IDS_TEST_STR                    357
#define IDS_CLOSE                       358
#define IDS_MULTI_MEDIA_KEY_TIP         359
#define IDS_SONG_INFO                   360
#define IDS_SELECT_FOLDER               361
#define IDS_FIND_SONGS                  362
#define IDI_FIND_SONGS                  362
#define IDI_FIND_SONGS_D                363
#define IDS_EXIT_FULL_SCREEN            363
#define IDI_FULL_SCREEN                 364
#define IDS_FULL_SCREEN                 364
#define IDI_FULL_SCREEN_D               365
#define IDS_WELCOM_TO_USE               365
#define IDI_FULL_SCREEN1                366
#define IDS_ERROR_MESSAGE               366
#define IDI_FULL_SCREEN1_D              367
#define IDS_CRASH_INFO                  367
#define IDS_ERROR1                      368
#define IDD_LISTEN_TIME_STATISTICS_DLG  368
#define IDS_HELP                        369
#define IDS_FILE_NOT_FOUND              370
#define IDD_DONATE_DIALOG               370
#define IDS_PLAY_SHORTCUT_CREATED       371
#define IDS_CREATE_PLAY_SHORTCUT_INFO   372
#define IDB_DONATE                      372
#define IDS_LISTEN_TIME                 373
#define IDS_LISTEN_TIME_FILE_DLG_FILTER 374
#define IDS_LISTEN_TIMES                375
#define IDI_MENU                        375
#define IDS_LISTEN_TIME_STATISTICS      376
#define IDI_MENU_D                      376
#define IDS_HIDE_MENU_BAR_TIP           377
#define IDR_PLAYLIST_BTN_MENU           377
#define IDS_LYRIC_PREVIEW               378
#define IDD_MEDIA_LIB_DIALOG            378
#define IDS_CRASH_ERROR_LOG_INFO        379
#define IDS_MAIN_MENU                   380
#define IDS_LYRIC_SAVE_FAILED           381
#define IDS_IDS_FILE_WRITE_FAILED       382
#define IDS_PLAYLIST                    382
#define IDD_SELECT_PLAYLIST_DIALOG      382
#define IDS_PLAYLIST_FILTER             383
#define IDD_INPUT_DLG                   384
#define IDS_CLEAR_PLAYLIST_WARNING      384
#define IDS_DEFAULT                     385
#define IDR_SELETE_PLAYLIST_POPUP_MENU  385
#define IDS_NEW_PLAYLIST                386
#define IDI_FILE_ICON                   386
#define IDS_INPUT_PLAYLIST_NAME         387
#define IDI_MEDIA_LIB                   387
#define IDS_RENAME_PLAYLIST             388
#define IDI_MEDIA_LIB_D                 388
#define IDS_CURRENT_FOLDER              389
#define IDD_FILE_RELATE_DIALOG          389
#define IDS_PLAYLIST_EXIST_WARNING      390
#define IDS_REMOVE_SAME_SONGS_INFO      391
#define IDD_TEST_DIALOG                 391
#define IDC_CURSOR1                     391
#define IDC_DRAG_CURSOR                 391
#define IDS_MEDIA_LIB                   392
#define IDI_FAVOURITE                   392
#define IDS_OPEN_MEDIA_LIB              393
#define IDI_FAVOURITE_D                 393
#define IDS_ADD_TO_PLAYLIST_FAILED_WARNING 394
#define IDI_HEART                       394
#define IDS_DESCRIPTION                 395
#define IDR_DESKTOP_LYRIC_POPUP_MENU    395
#define IDS_INCLUDE_SUB_DIR             396
#define IDI_CLOSE_D                     396
#define IDS_MY_FAVURITE                 397
#define IDI_LOCK_D                      397
#define IDS_ADD_TO_MA_FAVOURITE         398
#define IDI_DOUBLE_LINE_D               398
#define IDS_REMANE_FAILED               399
#define IDR_LRYIC_DEFAULT_STYLE_MENU    399
#define IDS_REMOVE_MY_FAVOURITE_WARNING 400
#define IDR_PLAYLIST_TOOLBAR_MENU       400
#define IDS_FILE_NAME_INVALID_WARNING   401
#define IDI_EDIT_D                      401
#define IDS_OPEN_URL                    402
#define IDI_ADD_D                       402
#define IDS_ADD_URL                     403
#define IDB_BITMAP1                     403
#define IDS_INPUT_URL_TIP               404
#define IDS_MCI_INIT_FAILED             405
#define IDS_MCI_NO_THIS_FUNCTION_WARNING 406
#define IDS_MCI_KERNAL_TIP              407
#define IDS_CLEAR_LISTEN_TIME_WARNING   408
#define IDS_PLAYLIST_NAME_EMPTY_WARNING 409
#define IDS_SEARCH_BOX_OPAQUE_TIP       410
#define IDS_ALBUM_COVER_COMPRESSED      410
#define IDS_TOW_COLOR_GRADIENT          411
#define IDS_THREE_COLOR_GRADIENT        412
#define IDD_MEDIA_CLASSIFY_DIALOG       412
#define IDS_NO_GRADIENT                 413
#define IDS_LRC                         414
#define IDS_SHOW_DESKTOP_LYRIC          415
#define IDR_MEDIA_LIB_POPUP_MENU        415
#define IDS_LOCK_DESKTOP_LYRIC          416
#define IDI_ALBUM_D                     416
#define IDS_CLOSE_DESKTOP_LYRIC         417
#define IDI_ARTIST_D                    417
#define IDS_LYRIC_DOUBLE_LINE           418
#define IDI_YEAR_D                      418
#define IDS_LYRIC_BACKGROUND_PENETRATE  419
#define IDD_FOLDER_EXPLORE_DIALOG       419
#define IDS_ULOCK_DESKTOP_LYRIC         420
#define IDS_ADD                         421
#define IDS_SORT                        422
#define IDI_FOLDER_EXPLORE_D            422
#define IDS_LIST                        423
#define IDI_EXPLORE_FOLDER              423
#define IDS_EDIT                        424
#define IDD_MEDIA_LIB_SETTING_DIALOG    424
#define IDS_DEFAULT_STYLE               425
#define IDS_MODIFY_DEFAULT_STYLE_WARNING 426
#define IDD_ADD_TO_PLAYLIST_DIALOG      426
#define IDS_RESTORE_DEFAULT_STYTLE_WARNING 427
#define IDS_URL_INVALID_WARNING         428
#define IDD_ALL_MEDIA_DIALOG            428
#define IDS_PROGRESS_INFO               429
#define IDS_BASS_MIX_LOAD_ERROR         430
#define IDS_BROWSE                      431
#define IDI_GENRE_D                     431
#define IDS_OTHER                       432
#define IDI_LYRIC_DELAY_D               432
#define IDS_SEARCH_ARTIST               433
#define IDI_LYRIC_FORWARD_D             433
#define IDS_SEARCH_ALBUM                434
#define IDI_RECENT_SONG_D               434
#define IDS_TEMP_PLAYLIST               435
#define IDI_ICON5                       435
#define IDI_FILE_PLAYLIST               435
#define IDS_GENRE                       436
#define IDB_DONATE_WECHAT               436
#define IDS_SEARCH_GENRE                437
#define IDI_STOP_NEW                    437
#define IDS_YEAR                        438
#define IDI_STOP_NEW_D                  438
#define IDS_SEARCH_YEAR                 439
#define IDI_PREVIOUS_NEW                439
#define IDS_TRACK_NUM                   440
#define IDI_PREVIOUS_NEW_D              440
#define IDS_FOLDER_EXPLORE              441
#define IDI_PLAY_NEW                    441
#define IDS_SEARCH_FORDER               442
#define IDI_PLAY_NEW_D                  442
#define IDS_BTN_SETTINGS                443
#define IDI_PAUSE_NEW                   443
#define IDS_MORE_PLAYLIST               444
#define IDI_PAUSE_NEW_D                 444
#define IDS_SEARCH_RESULT               445
#define IDI_NEXT_NEW                    445
#define IDS_UPDATING_MEDIA_LIB_INFO     446
#define IDI_NEXT_NEW_D                  446
#define IDS_ERROR_CODE                  447
#define IDS_UPDATE_MEDIA_LIB_TIP        448
#define IDR_LICENSE                     448
#define IDS_FILE_NOT_EXIST              449
#define IDI_SAVE_NEW_D                  449
#define IDS_FILE_CONNOT_BE_OPEND        450
#define IDI_MUSIC_D                     450
#define IDS_ALIGN_LEFT                  451
#define IDI_FILE_RELATE_D               451
#define IDS_ALIGN_RIGHT                 452
#define IDI_ONLINE_D                    452
#define IDS_CENTER                      453
#define IDI_PLAY_PAUSE_D                453
#define IDS_ALL_TRACKS                  454
#define IDI_CONVERT_D                   454
#define IDS_DO_NOT_SAVE                 455
#define IDI_DOWNLOAD_D                  455
#define IDS_AUTO_SAVE                   456
#define IDI_DOWNLOAD1_D                 456
#define IDS_INQUIRY                     457
#define IDI_HELP_D                      457
#define IDS_LYRIC_FORWARD               458
#define IDI_FF_NEW_D                    458
#define IDS_LYRIC_DELAY                 459
#define IDI_REW_NEW_D                   459
#define IDS_RECENT_PLAYED               460
#define IDI_SAVE_AS_D                   460
#define IDS_LAST_PLAYED_TIME            461
#define IDI_PLAYLIST_FLOAT_D            461
#define IDS_CLEAR_RECENT_PLAYLIST_INFO  462
#define IDI_PLAYLIST_DOCK_D             462
#define IDS_AB_REPEAT_A_SELECTED        463
#define IDI_STATISTICS_D                463
#define IDS_AB_REPEAT_ON_INFO           464
#define IDI_PIN_D                       464
#define IDS_AB_REPEAT                   465
#define IDI_EXIT_D                      465
#define IDS_INNER_LYRIC                 466
#define IDI_ALBUM_COVER_D               466
#define IDS_SHOW_ONLINE_HELP_INFO       467
#define IDI_ICON9                       467
#define IDI_DARK_MODE_D                 467
#define IDS_PLAYLIST_FILE_FILTER        468
#define IDS_SAVE_PLAYLIST_FILTER        469
#define IDB_PNG1                        469
#define IDB_DEFAULT_ALBUM_COVER         469
#define IDS_CREATE_MINI_MODE_SHORTCUT_INFO 470
#define IDD_LYRIC_RELATE_DIALOG         470
#define IDS_CREATE_DESKTOP_SHORTCUT_INFO 471
#define IDS_DELETE_SINGLE_FILE_INQUIRY  472
#define IDI_ICON10                      472
#define IDI_LYRIC_D                     472
#define IDS_ALL                         473
#define IDI_APP_DARK                    473
#define IDS_LAST_WEEK                   474
#define IDI_ICON12                      474
#define IDI_APP_LIGHT                   474
#define IDS_LAST_MONTH                  475
#define IDB_NOTIFY_ICON_PREVIEW         475
#define IDS_LAST_HALF_YEAR              476
#define IDB_NOTIFY_ICON_PREVIEW_LIGHT   476
#define IDS_LAST_YEAR                   477
#define IDI_DEFAULT_COVER_NOT_PLAYED    477
#define IDS_TODAY                       478
#define IDB_PNG2                        478
#define IDB_DEFAULT_ALBUM_COVER_NOT_PLAYED 478
#define IDS_LAST_THREE_DAYS             479
#define IDR_ACCELERATOR1                479
#define IDS_LICENSE_EXPLAIN             480
#define IDD_DIALOG5                     480
#define IDD_CLEAN_UP_RANGE_DIALOG       480
#define IDS_LICENSE                     481
#define IDS_FILE_EXIST_IN_PLAYLIST_INFO 482
#define IDS_IS_RELATED                  483
#define IDS_YES                         484
#define IDI_PLAY_RANDOM                 484
#define IDS_ALBUM_COVER_INFO            485
#define IDI_ICON13                      485
#define IDI_PLAY_RANDOM_D               485
#define IDS_INNER_ALBUM_COVER           486
#define IDD_PROPERTY_PARENT_DIALOG      486
#define IDS_WIDTH                       487
#define IDS_HEIGHT                      488
#define IDD_PROPERTY_ALBUM_COVER_DIALOG 488
#define IDS_BPP                         489
#define IDS_FILE_SIZE                   490
#define IDR_MENU3                       490
#define IDR_PROPERTY_COVER_MENU         490
#define IDS_DEFAULT_ICON                491
#define IDI_ICON11                      491
#define IDI_OK_D                        491
#define IDS_LIGHT_ICON                  492
#define IDR_CONTROL_MENU                492
#define IDS_DARK_ICON                   493
#define IDD_TAG_FROM_FILE_NAME_DIALOG   493
#define IDS_NO                          494
#define IDS_CONVERT_ERROR_FILE_CONNOT_OPEN 495
#define IDI_ICON14                      495
#define IDI_RENAME_D                    495
#define IDS_CONVERT_ERROR_ENCODE_CHANNEL_FAILED 496
#define IDS_CONVERT_ERROR_ENCODE_PARA_ERROR 497
#define IDS_CONVERT_ERROR_MIDI_NO_SF2   498
#define IDI_PLAY_TRACK                  498
#define IDS_CONTAIN_SUB_FOLDER          499
#define IDI_PLAY_TRACK_D                499
#define IDS_TYPE                        500
#define IDI_ICON15                      500
#define IDI_APP_DEBUG                   500
#define IDS_FILE_TYPE                   501
#define IDD_PROPERTY_ADVANCED_DIALOG    501
#define IDS_CLEAN_UP_MEDIA_WARNING      502
#define IDS_FILES_THAT_NOT_EXIST        503
#define IDR_PROPERTY_MENU               503
#define IDS_FILES_NOT_IN_MEDIA_LIB_DIR  504
#define IDI_ICON16                      504
#define IDI_TAG                         504
#define IDS_FILES_THAT_ERROR            505
#define IDD_SELECT_ITEM_DIALOG          505
#define IDS_IMAGE_FILE_FILTER           506
#define IDS_SEARCH_FILE_TYPE            507
#define IDI_ICON17                      507
#define IDI_LOCATE_D                    507
#define IDS_SEARCH_BITRATE              508
#define IDI_ICON18                      508
#define IDI_STAR                        508
#define IDS_PLAY_RANDOM                 509
#define IDS_FILE_PROPERTY               510
#define IDS_PROPERTY_TITLE_INFO         511
#define IDS_MULTI_VALUE                 512
#define IDS_TAG_BATCH_EDIT_INFO         513
#define IDS_GET_TAG_ONLINE_TITLE        514
#define IDS_GET_THIS                    515
#define IDS_NO_LYRICS_FOUND_INFO        516
#define IDS_CLEAR_HISTORY               517
#define IDS_CLEAR_HISTORY_INFO          518
#define IDS_RENAME                      519
#define IDS_RENAME_INFO                 520
#define IDS_PLAY_TRACK                  521
#define IDS_ADVANCED_PROPERTY           522
#define IDS_CONNOT_FIND_ARTIST_WARNING  523
#define IDS_CONNOT_FIND_ALBUM_WARNING   524
#define IDS_SCI_NOT_LOADED_ERROR_INFO   525
#define IDS_SELECT_ARTIST               526
#define IDS_LOCATE_TO_CURRENT           527
#define IDS_UI                          528
#define IDS_RATING                      529
#define IDS_UNRATED                     530
#define IDS_RANDOM_TRACK                531
#define IDS_NEXT_TRACK                  532
#define IDS_MEDIA_LIB_UPDATING_INFO     533
#define IDS_MINIMIZE                    534
#define IDI_CLOSE                       534
#define IDS_MAXIMIZE                    535
#define IDI_MINIMIZE                    535
#define IDS_RESTORE                     536
#define IDI_MINIMIZE_D                  536
#define IDI_MAXIMIZE                    537
#define IDS_SET_FILENAME_FORM           537
#define IDI_MAXIMIZE_D                  538
#define IDS_SET_MULTI_OUT_ALBUM_COVER_FILE_NAME 538
#define IDI_RESTORE                     539
#define IDS_DARK                        539
#define IDI_ICON19                      540
#define IDI_RESTORE_D                   540
#define IDS_LIGHT                       540
#define IDS_SHOW_HIDE_PLAYER            541
#define IDC_STATIC_PATH                 1001
#define IDC_LIST1                       1002
#define IDC_PATH_LIST                   1002
#define IDC_LYRIC_DOWN_LIST1            1002
#define IDC_SONG_LIST1                  1002
#define IDC_EQU_STYLES_LIST             1002
#define IDC_OUTPUT_DEVICE_INFO_LIST     1002
#define IDC_HOT_KEY_LIST                1002
#define IDC_STATIC_VERSION              1003
#define IDC_LIST3                       1003
#define IDC_DELETE_PATH_BUTTON          1004
#define IDC_TRACK_EDIT                  1009
#define IDC_PLAY_TRACK_BUTTON           1010
#define IDC_LIST_PREVIEW                1011
#define IDC_LIST_NEXT                   1012
#define IDC_BUTTON1                     1012
#define IDC_FIND_BUTTON                 1012
#define IDC_PREVIOUS_BUTTON             1012
#define IDC_INSERT_TAG_BUTTON           1012
#define IDC_CLEAN_DATA_FILE_BUTTON      1012
#define IDC_SEARCH_BUTTON2              1012
#define IDC_SHOW_LIST_BUTTON            1012
#define IDC_CLEAR_SEARCH_BUTTON         1012
#define IDC_ENCODER_CONFIG_BUTTON       1012
#define IDC_APPLY_BUTTON                1012
#define IDC_SET_BUTTON                  1012
#define IDC_SET_FONT                    1012
#define IDC_EXPORT_BUTTON               1012
#define IDC_PLAY_SELECTED               1012
#define IDC_NEW_PLAYLIST                1012
#define IDC_SETTINGS_BUTTON             1012
#define IDC_DONOT_RELATE_BUTTON         1012
#define IDC_DEFAULT_BUTTON              1012
#define IDC_SAVE_ALBUM_COVER_BUTTON     1012
#define IDC_GET_TAG_ONLINE_BUTTON       1012
#define IDC_TITLE_BUTTON                1012
#define IDC_VOLUME_UP                   1013
#define IDC_NEXT_BUTTON                 1013
#define IDC_SET_FONT2                   1013
#define IDC_PLAY_SELECTED2              1013
#define IDC_CLEAR_RECENT_PLAYED_LIST_BTN 1013
#define IDC_SHOW_OUT_ALBUM_COVER_CHK    1013
#define IDC_ARTIST_BUTTON               1013
#define IDC_VOLUME_DOWN                 1014
#define IDC_ALBUM_BUTTON                1014
#define IDC_SET_FONT_BUTTON             1014
#define IDC_PLAYLIST_LIST               1015
#define IDC_TRACK_BUTTON                1015
#define IDC_FIND_EDIT                   1016
#define IDC_YEAR_BUTTON                 1016
#define IDC_FIND_LIST                   1017
#define IDC_GENRE_BUTTON                1017
#define IDC_FIND_RESULT_STATIC          1018
#define IDC_COMMENT_BUTTON              1018
#define IDC_PATH_EDIT                   1019
#define IDC_FIND_INFO_STATIC            1019
#define IDC_ORIGINAL_BUTTON             1019
#define IDC_PATH_STATIC                 1020
#define IDC_OPTIONS_TAB                 1024
#define IDC_CHECK1                      1025
#define IDC_STOP_WHEN_ERROR             1025
#define IDC_FOLLOW_SYSTEM_COLOR_CHECK   1025
#define IDC_FIND_FILE_CHECK             1025
#define IDC_SKIP_EXIST_CHECK            1025
#define IDC_DOWNLOAD_TRANSLATE_CHECK1   1025
#define IDC_ENABLE_EQU_CHECK            1025
#define IDC_ENABLE_REVERB_CHECK         1025
#define IDC_ID3V2_FIRST_CHECK           1025
#define IDC_JOINT_STEREO_CHECK          1025
#define IDC_COPY_TAG_CHECK              1025
#define IDC_HOT_KEY_ENABLE_CHECK        1025
#define IDC_SHOW_SPECTRUM_IN_CORTANA    1025
#define IDC_SELECT_ALL_CHECK            1025
#define IDC_CLASSIFY_OTHER_CHECK        1025
#define IDC_FUZZY_MATCH_CHECK           1025
#define IDC_CHECK2                      1026
#define IDC_KARAOKE_DISP                1026
#define IDC_FIND_TITLE_CHECK            1026
#define IDC_DOWNLOAD_TRASNLATE_CHECK2   1026
#define IDC_SHOW_ALBUM_COVER_CHECK      1026
#define IDC_COVER_AUTO_DOWNLOAD_CHECK   1026
#define IDC_COPY_ALBUM_COVER_CHECK      1026
#define IDC_AUTO_PLAY_WHEN_START_CHECK  1026
#define IDC_ENABLE_GLABOL_MULTIMEDIA_KEY_CHECK 1026
#define IDC_ENABLE_GLOBAL_MULTIMEDIA_KEY_CHECK 1026
#define IDC_SHOW_TREE_TOOL_TIPS_CHECK   1026
#define IDC_UPDATE_MEDIA_LIB_CHK        1026
#define IDC_FONT_NAME_EDIT              1027
#define IDC_FIND_ARTIST_CHECK           1027
#define IDC_KARAOKE_DISP2               1027
#define IDC_LYRIC_FUZZY_MATCH           1027
#define IDC_SHOW_SPECTRUM_CHECK         1027
#define IDC_LYRIC_AUTO_DOWNLOAD_CHECK   1027
#define IDC_SHOW_PLAY_STATE_ICON_CHECK  1027
#define IDC_OPEN_TARGET_DIR_CHECK       1027
#define IDC_FONT_SIZE_EDIT              1028
#define IDC_CHECK5                      1028
#define IDC_FIND_ALBUM_CHECK            1028
#define IDC_SHOW_LYRIC_IN_CORTANA       1028
#define IDC_DOWNLOAD_WHEN_TAG_FULL_CHECK 1028
#define IDC_ARTIST_CHECK                1028
#define IDC_SHOW_NEXT_CHECK             1028
#define IDC_CONTINUE_WHEN_SWITCH_PLAYLIST_CHECK 1028
#define IDC_LYRIC_PATH_EDIT             1029
#define IDC_BITRATE_CHECK               1029
#define IDC_SHOW_NEXT_CHECK2            1029
#define IDC_SHOW_FPS_CHECK              1029
#define IDC_EXPLORE_LYRIC_BUTTON        1030
#define IDC_ALL_CHECK                   1030
#define IDC_FONT_SIZE_EDIT2             1030
#define IDC_SLIDER1                     1031
#define IDC_TRANSPARENT_SLIDER          1031
#define IDC_RECENT_CHECK                1031
#define IDC_SLIDER2                     1032
#define IDC_RECENT_CHECK2               1032
#define IDC_BITRATE_CHECK2              1032
#define IDC_RATING_CHECK                1032
#define IDC_TRANSPARENT_STATIC          1033
#define IDC_SLIDER3                     1033
#define IDC_FOLDER_EXPLORE_CHECK        1033
#define IDC_FILE_NAME_EDIT              1034
#define IDC_SLIDER4                     1034
#define IDC_FILE_PATH_EDIT              1035
#define IDC_CHECK3                      1035
#define IDC_SHOW_TASKBAR_PROGRESS       1035
#define IDC_SLIDER5                     1035
#define IDC_ALBUM_COVER_BACKGROUND_CHECK 1035
#define IDC_CHECK_UPDATE_CHECK          1035
#define IDC_ADD_NUMBER_CHECK            1035
#define IDC_CORTANA_OPAQUE              1035
#define IDC_SEARCH_BOX_OPAQUE_CHECK     1035
#define IDC_DISABLE_DRAGE_SORT_CHECK    1035
#define IDC_FILE_TYPE_EDIT              1036
#define IDC_SLIDER6                     1036
#define IDC_EDIT4                       1037
#define IDC_SONG_LENGTH_EDIT            1037
#define IDC_SYSLINK1                    1037
#define IDC_SLIDER7                     1037
#define IDC_PROGRESS_STATIC             1038
#define IDC_FILE_SIZE_EDIT              1038
#define IDC_SLIDER8                     1038
#define IDC_TIME_STATIC                 1039
#define IDC_FILE_SIZE_EDIT2             1039
#define IDC_BIT_RATE_EDIT               1039
#define IDC_SLIDER9                     1039
#define IDC_SET_PROGRESS_COLOR_BUTTON   1040
#define IDC_TITEL_EDIT                  1040
#define IDC_SLIDER10                    1040
#define IDC_COLOR_STATIC                1041
#define IDC_ARTIST_EDIT                 1041
#define IDC_COLOR_STATIC2               1042
#define IDC_COLOR_STATIC1               1042
#define IDC_ITEM_STATIC                 1042
#define IDC_COLOR_STATIC3               1043
#define IDC_ALBUM_EDIT                  1043
#define IDC_COLOR_STATIC4               1044
#define IDC_HELP_EDIT                   1044
#define IDC_BIT_RATE_EDIT2              1044
#define IDC_LYRIC_FILE_EDIT             1044
#define IDC_COLOR_STATIC5               1045
#define IDC_TAG_TYPE_STATIC             1045
#define IDC_COLOR_STATIC6               1046
#define IDC_DEBUG_INFO_STATIC           1046
#define IDC_COLOR_STATIC7               1047
#define IDC_LYRIC_STATIC                1047
#define IDC_TIME_STATIC1                1048
#define IDC_PROGRESS_STATIC1            1049
#define IDC_YEAR_EDIT                   1050
#define IDC_SPECTRAL_STATIC             1050
#define IDC_GENRE_EDIT                  1051
#define ID_M_PLAY_PAUSE                 1051
#define IDC_COMMENT_EDIT                1052
#define ID_M_PREVIOUS                   1052
#define IDC_YEAR_EDIT2                  1053
#define ID_M_NEXT                       1053
#define IDC_STOP                        1054
#define IDC_PREVIOUS                    1055
#define IDC_PLAY_PAUSE                  1056
#define IDC_NEXT                        1057
#define IDC_SAVE_IN_OFFSET_TAG          1058
#define IDC_SAVE_IN_TIME_TAG            1059
#define IDC_REPLACE_TAG_BUTTON          1059
#define IDC_SAVE_LYRIC_BUTTON           1060
#define IDC_EDIT1                       1061
#define IDC_DELETE_TAG__BUTTON          1062
#define IDC_SAVE_AS_BUTTON5             1063
#define IDC_OPEN_LYRIC_BUTTON           1064
#define IDC_EDIT2                       1065
#define IDC_LYRIC_PATH_EDIT2            1065
#define IDC_ARTIST_EDIT1                1065
#define IDC_VBR_QUA_EDIT                1065
#define IDC_SPIN1                       1066
#define IDC_SIZE_STATIC                 1067
#define IDC_TITLE_EDIT1                 1069
#define IDC_DOWNLOAD_SELECTED           1070
#define IDC_START_DOWNLOAD              1071
#define IDC_COMBO1                      1072
#define IDC_INFO_STATIC                 1073
#define IDC_ABR_RATE_COMBO              1073
#define IDC_HIGHLIGHT_GRADIENT_COMBO    1073
#define IDC_STATIC_INFO                 1074
#define IDC_LIST2                       1075
#define IDC_STATIC1                     1076
#define IDC_SAVE_TO_SONG_FOLDER         1077
#define IDC_RADIO2                      1078
#define IDC_SAVE_TO_LYRIC_FOLDER        1078
#define IDC_FIND_ALL_PLAYLIST_RADIO     1078
#define IDC_MCI_RADIO                   1078
#define IDC_COPY_RADIO                  1078
#define IDC_COMBO2                      1079
#define IDC_SAVE_TO_SONG_FOLDER1        1080
#define IDC_SAVE_TO_LYRIC_FOLDER1       1081
#define IDC_BUTTON2                     1082
#define IDC_SELECTED_SAVE_AS            1082
#define IDC_SAVE_TO_FILE_BUTTON         1082
#define IDC_BROWSE_BUTTON               1082
#define IDC_DEFAULT_STYLE               1082
#define IDC_MEDIA_LIB_SETTINGS_BTN      1082
#define IDC_RESTORE_DEFAULT_BUTTON      1082
#define IDC_LOCAL_SEARCH_BUTTON         1082
#define IDC_GET_TAG_FROM_FILE_NAME_BUTTON 1082
#define IDC_REFRESH_MEDIA_LIB_BUTTON    1082
#define IDC_TAB1                        1083
#define IDC_BROWSE_BUTTON2              1083
#define IDC_REVERB_MIX_SLIDER           1084
#define IDC_REVERB_TIME_SLIDER          1085
#define IDC_REVERB_MIX_STATIC           1086
#define IDC_REVERB_TIME_STATIC          1087
#define IDC_SYSLINK2                    1088
#define IDC_LICENSE_SYSLINK             1089
#define IDC_SPECTRUM_HEIGHT_SLIDER      1090
#define IDC_SPECTRUM_HEIGHT_STATIC      1091
#define IDC_MINI_PROGRESS_STATIC        1092
#define IDC_BACKGROUND_TRANSPARENCY_SLIDER 1092
#define IDC_FIND_CURRENT_PLAYLIST_RADIO 1093
#define IDC_SPECTRUM_HEIGHT_STATIC2     1093
#define IDC_BACKGROUND_TRANSPARENCY_STATIC 1093
#define IDC_GENRE_COMBO                 1094
#define IDC_GAUSS_BLURE_RADIUS_SLIDER   1094
#define IDC_CHECK4                      1095
#define IDC_LYRIC_DOUBLE_LINE_CHECK     1095
#define IDC_USE_OUT_IMAGE_CHECK         1095
#define IDC_MIDI_USE_INNER_LYRIC_CHECK  1095
#define IDC_SOUND_FADE_CHECK            1095
#define IDC_CHANGE_FREQ_CHECK           1095
#define IDC_IGNORE_EXIST_CHECK          1095
#define IDC_BUTTON3                     1096
#define IDC_START_CONVERT_BUTTON        1096
#define IDC_BACKGROUND_TRANSPARENCY_STATIC2 1096
#define IDC_GAUSS_BLUR_RADIUS_STATIC    1096
#define IDC_RECORD_BUTTON               1096
#define IDC_KEEP_DISPLAY_CHECK          1096
#define IDC_BROWSE_BUTTON1              1096
#define IDC_GET_TAG_FROM_LYRIC_BUTTON   1096
#define IDC_ALBUM_FIT_COMBO             1097
#define IDC_PAUSE_RESUME_BUTTON         1097
#define IDC_LYRIC_DOUBLE_LINE_CHECK2    1097
#define IDC_OPEN_FOLDER                 1098
#define IDC_STOP_BUTTON                 1098
#define IDC_LOCK_DESKTOP_LYRIC_CHECK    1098
#define IDC_CORTANA_COLOR_COMBO         1099
#define IDC_SHOW_ALBUM_COVER_IN_CORTANA 1101
#define IDC_CORTANA_ICON_DEAT_CHECK     1102
#define IDC_SEARCH_EDIT                 1103
#define IDC_SHOW_LYRIC_IN_CORTANA2      1103
#define IDC_DEFAULT_COVER_NAME_EDIT     1104
#define IDC_COVER_DOWN_LIST             1105
#define IDC_SEARCH_BUTTON               1106
#define IDC_TITLE_EDIT                  1107
#define IDC_GITHUB_SYSLINK              1108
#define IDC_SF2_PATH_EDIT               1109
#define IDC_DONATE_SYSLINK              1109
#define IDC_OUT_FORMAT_COMBO            1110
#define IDC_OUT_DIR_EDIT                1111
#define IDC_CBR_RADIO                   1112
#define IDC_OUT_NAME_EDIT               1112
#define IDC_ABR_RADIO                   1113
#define IDC_CBR_RADIO2                  1113
#define IDC_VBR_RADIO                   1114
#define IDC_USER_RADIO                  1115
#define IDC_CBR_RATE_COMBO              1116
#define IDC_ENCODE_CMDLINE_EDIT         1117
#define IDC_QUALITY_SLIDER              1119
#define IDC_BITRATE_COMBO               1120
#define IDC_ADD_BUTTON                  1121
#define IDC_VBR_QUALITY_COMBO           1121
#define IDC_TARGET_FILE_EXIST_COMBO     1122
#define IDC_DELETE_BUTTON               1123
#define IDC_CLEAR_BUTTON                1124
#define IDC_BACKGROUND_GAUSS_BLUR_CHECK 1124
#define IDC_MOVE_UP_BUTTON              1125
#define IDC_LYRIC_BACKGROUND_CHECK      1125
#define IDC_BUTTON8                     1126
#define IDC_MOVE_DOWN_BUTTON            1126
#define IDC_SAVE_BUTTON                 1126
#define IDC_CHECK6                      1126
#define IDC_DARK_MODE_CHECK             1126
#define IDC_SHOW_DESKTOP_LYRIC          1126
#define IDC_CLEAN_NOT_EXIST_CHECK       1126
#define IDC_AUTO_RUN_CHECK              1126
#define IDC_DISABLE_DELETE_FROM_DISK_CHECK 1126
#define IDC_RECORDE_INPUT_COMBO         1127
#define IDC_CLEAN_NOT_IN_MEDIA_LIB_DIR_CHECK 1127
#define IDC_OUTPUT_DEVICE_COMBO         1128
#define IDC_FORMAT_LIST                 1129
#define IDC_HOTKEY1                     1130
#define IDC_STATIC_COPYRIGHT            1131
#define IDC_MINIMIZE_TO_NOTIFY_RADIO    1132
#define IDC_RADIO3                      1133
#define IDC_EXIT_PROGRAM_RADIO          1133
#define IDC_USE_INNER_IMAGE_FIRST_CHECK 1133
#define IDC_LYRIC_COMPATIBLE_MODE       1134
#define IDC_UNASSOCIATE_LINK            1135
#define IDC_SHOW_DEFAULT_ALBUM_ICON_CHK 1135
#define IDC_DONATE_STATIC               1136
#define IDC_LYRIC_COMPATIBLE_MODE2      1136
#define IDC_SEARCH_BOX_TRANSPARENT_IN_WHITE_MODE 1136
#define IDC_INPUT_EDIT                  1138
#define IDC_BASS_RADIO                  1139
#define IDC_TEXT_COLOR1_STATIC          1140
#define IDC_TEXT_COLOR2_STATIC          1142
#define IDC_TEXT_GRADIENT_COMBO         1143
#define IDC_HIGHLIGHT_COLOR1_STATIC     1144
#define IDC_HIGHLIGHT_COLOR2_STATIC     1145
#define IDC_LYRIC_OPACITY_STATIC        1146
#define IDC_LYRIC_OPACITY_SLIDER        1147
#define IDC_HIDE_LYRIC_WITHOUT_LYRIC_CHECK 1148
#define IDC_HIDE_LYRIC_WITHOUT_LYRIC_CHECK2 1149
#define IDC_HIDE_LYRIC_PAUSE_CHECK      1149
#define IDC_TEST_TOOLBAR                1149
#define IDC_HIDE_LYRIC_WITHOUT_LYRIC_CHECK3 1150
#define IDC_PLAYLIST_TOOLBAR            1150
#define IDC_ENABLE_BACKGROUND_CHECK     1151
#define IDC_SHOW_UNLOCK_WHEN_LOCKED     1151
#define IDC_TEST_PROGRESS_BAR           1152
#define IDC_PROGRESS_TEXT               1153
#define IDC_PROGRESS_BAR                1154
#define IDC_MFCEDITBROWSE1              1155
#define IDC_FREQ_COMBO                  1156
#define IDC_CLASSIFY_LIST               1158
#define IDC_SONG_LIST                   1159
#define IDC_FOLDER_EXPLORE_TREE         1160
#define IDC_DIR_LIST                    1161
#define IDC_LOW_FREQ_IN_CENTER_CHECK    1162
#define IDC_ALIGNMENT_COMBO             1163
#define IDC_LYRIC_SAVE_COMBO            1164
#define IDC_USE_INNER_LYRIC_CHECK       1165
#define IDC_LYRIC_FILE_STATIC           1166
#define IDC_ALIGNMENT_COMBO2            1166
#define IDC_PLAYLIST_DISPLAY_MODE_OMBO  1167
#define IDC_ALIGNMENT_COMBO3            1167
#define IDC_DESKTOP_LYRIC_ALIGNMENT_COMBO 1167
#define IDC_RECENT_PLAYED_RANGE_OMBO    1168
#define IDC_DEFAULT_ALBUM_COVER_HQ      1168
#define IDC_UI_INTERVAL_EDIT            1169
#define IDC_SEARCH_RESULT_LIST          1170
#define IDC_DELETE_FILE_BUTTON          1171
#define IDC_LYRIC_NAME_EDIT             1172
#define IDC_PREVIEW_STATIC              1173
#define IDC_CHECK7                      1174
#define IDC_NOTIFY_ICON_AUTO_ADAPT_CHECK 1174
#define IDC_SHOW_PLAYLIST_TOOLTIP_CHECK 1174
#define IDC_CHECK8                      1175
#define IDC_BTN_ROUND_CORNERS_CHECK     1175
#define IDC_UI_STATIC                   1176
#define IDC_ALBUM_CHECK                 1177
#define IDC_GENRE_CHECK                 1178
#define IDC_YEAR_CHECK                  1179
#define IDC_FILE_TYPE_CHECK             1180
#define IDC_DEFAULT_BACKGROUND_PATH_EDIT 1182
#define IDC_INSERT_RADIO                1183
#define IDC_USE_DESKTOP_BACKGROUND_CHECK 1184
#define IDC_ID3V2_TYPE_COMBO            1185
#define IDC_GITHUB_RADIO                1186
#define IDC_GITEE_RADIO                 1187
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_OPEN                         32773
#define ID_FILE_OPEN_FOLDER             32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_PLAY_PAUSE                   32778
#define ID_STOP                         32779
#define ID_32780                        32780
#define ID_PREVIOUS                     32781
#define ID_32782                        32782
#define ID_NEXT                         32783
#define ID_32784                        32784
#define ID_32785                        32785
#define ID_32786                        32786
#define ID_REW                          32787
#define ID_FF                           32788
#define ID_32789                        32789
#define ID_32790                        32790
#define ID_32791                        32791
#define ID_32792                        32792
#define ID_SET_PATH                     32793
#define ID_FIND                         32794
#define ID_EXPLORE_PATH                 32795
#define ID_32796                        32796
#define ID_32797                        32797
#define ID_32798                        32798
#define ID_32799                        32799
#define ID_32800                        32800
#define ID_32801                        32801
#define ID_32802                        32802
#define ID_32803                        32803
#define ID_PLAY_ORDER                   32804
#define ID_PLAY_SHUFFLE                 32805
#define ID_PLAY_RANDOM                  32806
#define ID_LOOP_PLAYLIST                32807
#define ID_LOOP_TRACK                   32808
#define ID_PLAY_TRACK                   32809
#define ID_SET_FONT                     32810
#define ID_STOP_WHEN_ERROR              32811
#define ID_32812                        32812
#define ID_32813                        32813
#define ID_32814                        32814
#define ID_32815                        32815
#define ID_TRANSPARENCY_100             32816
#define ID_TRANSPARENCY_80              32817
#define ID_TRANSPARENCY_60              32818
#define ID_TRANSPARENCY_40              32819
#define ID_32820                        32820
#define ID_KARAOKE_DISP                 32821
#define ID_32822                        32822
#define ID_REFRESH_PLAYLIST             32823
#define ID_32824                        32824
#define ID_OPTION_SETTINGS              32825
#define ID_OPTION_SETTINGS2             32826
#define ID_RELOAD_PLAYLIST              32827
#define ID_32828                        32828
#define ID_Menu                         32829
#define ID_PLAY_ITEM                    32830
#define ID_TEST                         32831
#define ID_PROPERTY                     32832
#define ID_ITEM_PROPERTY                32833
#define ID_TEST_DIALOG                  32834
#define ID_REMOVE_FROM_PLAYLIST         32835
#define ID_32836                        32836
#define ID_32837                        32837
#define ID_CLEAR_PLAYLIST               32838
#define ID_32839                        32839
#define ID_EXPLORE_TRACK                32840
#define ID_32841                        32841
#define ID_32842                        32842
#define ID_RE_INI_BASS                  32843
#define ID_32844                        32844
#define ID_32845                        32845
#define ID_32846                        32846
#define ID_32847                        32847
#define ID_32848                        32848
#define ID_32849                        32849
#define ID_SORT_BY_FILE                 32850
#define ID_SORT_BY_PATH                 32851
#define ID_SORT_BY_TITLE                32852
#define ID_SORT_BY_ARTIST               32853
#define ID_SORT_BY_ALBUM                32854
#define ID_SORT_BY_TRACK                32855
#define ID_SORT_BY_MODIFIED_TIME        32856
#define ID_DELETE_FROM_DISK             32857
#define ID_32858                        32858
#define ID_32859                        32859
#define ID_32860                        32860
#define ID_32861                        32861
#define ID_DISP_FILE_NAME               32862
#define ID_DISP_TITLE                   32863
#define ID_DISP_ARTIST_TITLE            32864
#define ID_DISP_TITLE_ARTIST            32865
#define ID_32866                        32866
#define ID_MINI_DOEDE                   32867
#define ID_32868                        32868
#define ID_32869                        32869
#define ID_MINI_MODE_EXIT               32870
#define ID_SONG_INFO                    32871
#define ID_MINI_MODE                    32872
#define ID_32873                        32873
#define ID_SET_TEXT_COLOR               32874
#define ID_32875                        32875
#define ID_RELOAD_LYRIC                 32876
#define ID_SONG_INFO1                   32877
#define ID_32878                        32878
#define ID_32879                        32879
#define ID_COPY_CURRENT_LYRIC           32880
#define ID_COPY_ALL_LYRIC               32881
#define ID_32882                        32882
#define ID_32883                        32883
#define ID_LYRIC_FORWARD_0_5_SEC        32884
#define ID_LYRIC_FORWARD                32885
#define ID_LYRIC_DELAY                  32886
#define ID_32887                        32887
#define ID_SAVE_MODIFIED_LYRIC          32888
#define ID_32889                        32889
#define ID_EDIT_LYRIC                   32890
#define ID_32891                        32891
#define ID_DOWNLOAD_LYRIC               32892
#define ID_32893                        32893
#define ID_LYRIC_BATCH_DOWNLOAD         32894
#define ID_32895                        32895
#define ID_32896                        32896
#define ID_DELETE_LYRIC                 32897
#define ID_32898                        32898
#define ID_32899                        32899
#define ID_DARK_MODE                    32900
#define ID_32901                        32901
#define ID_32902                        32902
#define ID_FOLLOW_MAIN_COLOR            32903
#define ID_32904                        32904
#define ID_32905                        32905
#define ID_32906                        32906
#define ID_32907                        32907
#define ID_32908                        32908
#define ID_32909                        32909
#define ID_32910                        32910
#define ID_LYRIC_OPEN                   32911
#define ID_LRYIC_SAVE                   32912
#define ID_LYRIC_SAVE_AS                32913
#define ID_LYRIC_EXIT                   32914
#define ID_INSERT_TAG_BUTTON            32915
#define ID_INSERT_TAG                   32916
#define ID_REPLACE_TAG                  32917
#define ID_DELETE_TAG                   32918
#define ID_32919                        32919
#define ID_32920                        32920
#define ID_32921                        32921
#define ID_32922                        32922
#define ID_32923                        32923
#define ID_LYRIC_FIND                   32924
#define ID_LYRIC_REPLACE                32925
#define IDC_LYRIC_OPEN                  32926
#define ID_LYRIC_SAVE                   32927
#define ID_32928                        32928
#define ID_FIND_NEXT                    32929
#define ID_32930                        32930
#define ID_EQUALIZER                    32931
#define ID_32932                        32932
#define ID_EXPLORE_ONLINE               32933
#define ID_32934                        32934
#define ID_32935                        32935
#define ID_LYRIC_DOWNLOAD               32936
#define ID_LD_LYRIC_DOWNLOAD            32937
#define ID_LD_LYRIC_SAVEAS              32938
#define ID_32939                        32939
#define ID_32940                        32940
#define ID_32941                        32941
#define ID_32942                        32942
#define ID_32943                        32943
#define ID_LD_COPY_TITLE                32944
#define ID_LD_COPY_ALBUM                32945
#define ID_LD_COPY_ID                   32946
#define ID_LD_VIEW_ONLINE               32947
#define ID_LD_COPY_ARTIST               32948
#define ID_32949                        32949
#define ID_32950                        32950
#define ID_FD_PLAY                      32951
#define ID_FD_OPEN_FILE_LOCATION        32952
#define ID_32953                        32953
#define ID_FD_COPY_TEXT                 32954
#define ID_BROWSE_LYRIC                 32955
#define ID_32956                        32956
#define ID_TRANSLATE_TO_SIMPLIFIED_CHINESE 32957
#define ID_32958                        32958
#define ID_TRANSLATE_TO_TRANDITIONAL_CHINESE 32959
#define ID_LE_TRANSLATE_TO_SIMPLIFIED_CHINESE 32960
#define ID_LE_TRANSLATE_TO_TRANDITIONAL_CHINESE 32961
#define ID_ALBUM_COVER_SAVE_AS          32962
#define ID_LYRIC_INSERT_TAG             32963
#define ID_LYRIC_REPLACE_TAG            32964
#define ID_LYRIC_DELETE_TAG             32965
#define ID_32967                        32967
#define ID_PLAY_PATH                    32968
#define ID_32969                        32969
#define ID_DELETE_PATH                  32970
#define ID_32971                        32971
#define ID_BROWSE_PATH                  32972
#define ID_32973                        32973
#define ID_CLEAR_INVALID_PATH           32974
#define ID_DOWNLOAD_ALBUM_COVER         32975
#define ID_32976                        32976
#define ID_CURRENT_EXPLORE_ONLINE       32977
#define ID_32978                        32978
#define ID_DELETE_ALBUM_COVER           32979
#define ID_32980                        32980
#define ID_32981                        32981
#define ID_COPY_FILE_TO                 32982
#define ID_MOVE_FILE_TO                 32983
#define ID_FORMAT_CONVERT               32984
#define ID_32985                        32985
#define ID_FORMAT_CONVERT1              32986
#define ID_32987                        32987
#define ID_ADD_FILE                     32988
#define ID_32989                        32989
#define ID_DELETE_SELECT                32990
#define ID_CLEAR_LIST                   32991
#define ID_MOVE_UP                      32992
#define ID_MOVE_DOWN                    32993
#define ID_32994                        32994
#define ID_EDIT_TAG_INFO                32995
#define ID_32996                        32996
#define ID_RECORDER                     32997
#define ID_SUPPORTED_FORMAT             32998
#define ID_32999                        32999
#define ID_VOLUME_UP                    33000
#define ID_VOLUME_DOWN                  33001
#define ID_SHOW_PLAY_LIST               33002
#define ID_MENU_EXIT                    33003
#define ID_33004                        33004
#define ID_MINIMODE_RESTORE             33005
#define ID_33006                        33006
#define ID_MINI_MIDE_MINI               33007
#define ID_MINI_MIDE_MINIMIZE           33008
#define ID_33009                        33009
#define ID_SHOW_PLAYLIST                33010
#define ID_33011                        33011
#define ID_SHOW_MENU_BAR                33012
#define ID_33013                        33013
#define ID_FULL_SCREEN                  33014
#define ID_33015                        33015
#define ID_CREATE_PLAY_SHORTCUT         33016
#define ID_33017                        33017
#define ID_LISTEN_STATISTICS            33018
#define ID_33019                        33019
#define ID_LD_PREVIEW                   33020
#define ID_33021                        33021
#define ID_33022                        33022
#define ID_ALWAYS_ON_TOP                33023
#define ID_33024                        33024
#define ID_33025                        33025
#define ID_FLOAT_PLAYLIST               33026
#define ID_33027                        33027
#define ID_33028                        33028
#define ID_DOCKED_PLAYLIST              33029
#define ID_FLOATED_PLAYLIST             33030
#define ID_33031                        33031
#define ID_FILE_OPEN_PALYLIST           33032
#define ID_33033                        33033
#define ID_33034                        33034
#define ID_33035                        33035
#define ID_PLAYLIST_ADD_FILE            33036
#define ID_EMPTY_PLAYLIST               33037
#define ID_33038                        33038
#define ID_33039                        33039
#define ID_33040                        33040
#define ID_PLAY_PLAYLIST                33041
#define ID_RENAME_PLAYLIST              33042
#define ID_DELETE_PLAYLIST              33043
#define ID_33044                        33044
#define ID_MOVE_PLAYLIST_ITEM_UP        33045
#define ID_MOVE_PLAYLIST_ITEM_DOWN      33046
#define ID_33047                        33047
#define ID_REMOVE_SAME_SONGS            33048
#define ID_33049                        33049
#define ID_ADD_TO_NEW_PLAYLIST          33050
#define ID_ADD_TO_DEFAULT_PLAYLIST      33051
#define ID_ADD_TO_MY_FAVOURITE          33052
#define ID_FILE_RELATE                  33095
#define ID_TOOL_FILE_RELATE             33096
#define ID_ADD_TO_OTHER_PLAYLIST        33097
#define ID_33098                        33098
#define ID_MENU_ADD                     33099
#define ID_MENU_DELETE                  33100
#define ID_33101                        33101
#define ID_PLAYLIST_ADD_FOLDER          33102
#define ID_ADD_REMOVE_FROM_FAVOURITE    33103
#define ID_REMOVE_INVALID_ITEM          33104
#define ID_REMOVE_INVALID_ITEMS         33105
#define ID_33106                        33106
#define ID_NEW_PLAYLIST                 33107
#define ID_33108                        33108
#define ID_FILE_OPEN_URL                33109
#define ID_33110                        33110
#define ID_PLAYLIST_ADD_URL             33111
#define ID_33112                        33112
#define ID_LYRIC_DISPLAYED_DOUBLE_LINE  33113
#define ID_LOCK_DESKTOP_LRYIC           33114
#define ID_33115                        33115
#define ID_CLOSE_DESKTOP_LYRIC          33116
#define ID_33117                        33117
#define ID_33118                        33118
#define ID_33119                        33119
#define ID_33120                        33120
#define ID_LYRIC_DEFAULT_STYLE1         33121
#define ID_LYRIC_DEFAULT_STYLE2         33122
#define ID_LYRIC_DEFAULT_STYLE3         33123
#define ID_LYRIC_USER_DEFINE            33124
#define ID_33125                        33125
#define ID_LYRIC_BACKGROUND_PENETRATE   33126
#define ID_PLAYLIST_SELECT_ALL          33127
#define ID_PLAYLIST_SELECT_NONE         33128
#define ID_PLAYLIST_SELECT_REVERT       33129
#define ID_33130                        33130
#define ID_2_33131                      33131
#define ID_LYRIC_DEFAULT_STYLE1_MODIFY  33132
#define ID_LYRIC_DEFAULT_STYLE2_MODIFY  33133
#define ID_LYRIC_DEFAULT_STYLE3_MODIFY  33134
#define ID_33135                        33135
#define ID_RESTORE_DEFAULT_STYLE        33136
#define ID_33137                        33137
#define ID_ONLINE_HELP                  33138
#define ID_33139                        33139
#define ID_33140                        33140
#define ID_33141                        33141
#define ID_SPEED_UP                     33142
#define ID_SLOW_DOWN                    33143
#define ID_ORIGINAL_SPEED               33144
#define ID_ADD_TO_NEW_PALYLIST_AND_PLAY 33145
#define ID_33146                        33146
#define ID_PLAY_ITEM_IN_FOLDER_MODE     33147
#define ID_COPY_TEXT                    33148
#define ID_ALWAYS_SHOW_STATUS_BAR       33149
#define ID_SHOW_MAIN_WINDOW             33150
#define ID_AB_REPEAT                    33151
#define ID_33152                        33152
#define ID_SET_A_POINT                  33153
#define ID_SET_B_POINT                  33154
#define ID_RESET_AB_REPEAT              33155
#define ID_AB33156                      33156
#define ID_NEXT_AB_REPEAT               33157
#define ID_SAVE_CURRENT_PLAYLIST_AS     33158
#define ID_33159                        33159
#define ID_FILE_OPEN_PLAYLIST           33160
#define ID_33161                        33161
#define ID_EXPORT_CURRENT_PLAYLIST      33162
#define ID_33163                        33163
#define ID_SAVE_AS_NEW_PLAYLIST         33164
#define ID_CREATE_DESKTOP_SHORTCUT      33165
#define ID_CREATE_MINI_MODE_SHORT_CUT   33166
#define ID_REMOVE_CURRENT_FROM_PLAYLIST 33167
#define ID_DELETE_CURRENT_FROM_DISK     33168
#define ID_33169                        33169
#define ID_MINI_MODE_ALWAYS_ON_TOP      33170
#define ID_ALWAYS_USE_EXTERNAL_ALBUM_COVER 33171
#define ID_33173                        33173
#define ID_LRYIC_MERGE_SAME_TIME_TAG    33174
#define ID_LYRIC_SWAP_TEXT_AND_TRANSLATION 33175
#define ID_33176                        33176
#define ID_LYRIC_TIME_TAG_FORWARD       33177
#define ID_                             33178
#define ID_LYRIC_TIME_TAG_DELAY         33179
#define ID_33180                        33180
#define ID_RELATE_LOCAL_LYRIC           33181
#define ID_33182                        33182
#define ID_ALBUM_COVER_INFO             33183
#define ID_UNLINK_LYRIC                 33184
#define ID_SHOW_DESKTOP_LYRIC           33185
#define ID_33186                        33186
#define ID_33187                        33187
#define ID_CONTAIN_SUB_FOLDER           33188
#define ID_33189                        33189
#define ID_33190                        33190
#define ID_ACCENDING_ORDER              33191
#define ID_DESENDING_ORDER              33192
#define ID_33193                        33193
#define ID_INVERT_PLAYLIST              33194
#define ID_33195                        33195
#define ID_HELP_UPDATE_LOG              33196
#define ID_LD_RELATE                    33197
#define ID_COVER_BROWSE                 33198
#define ID_COVER_DELETE                 33199
#define ID_1_33200                      33200
#define ID_COVER_SAVE_AS                33201
#define ID_LISTCTRL_33202               33202
#define ID_33203                        33203
#define ID_RENAME                       33204
#define ID_33205                        33205
#define ID_33206                        33206
#define ID_33207                        33207
#define ID_EMBED_LYRIC_TO_AUDIO_FILE    33208
#define ID_DELETE_LYRIC_FROM_AUDIO_FILE 33209
#define ID_SWITCH_UI                    33210
#define ID_SHOW_LYRIC_TRANSLATE         33320
#define ID_COPY_ALL_TEXT                33321
#define ID_VIEW_ARTIST                  33322
#define ID_LOCATE_TO_CURRENT            33323
#define ID_VIEW_ALBUM                   33324
#define ID_33325                        33325
#define ID_33326                        33326
#define ID_33327                        33327
#define ID_33328                        33328
#define ID_33329                        33329
#define ID_33330                        33330
#define ID_33331                        33331
#define ID_RATING_1                     33332
#define ID_RATING_2                     33333
#define ID_RATING_3                     33334
#define ID_RATING_4                     33335
#define ID_RATING_5                     33336
#define ID_RATING_NONE                  33337
#define ID_33338                        33338
#define ID_USE_STANDARD_TITLE_BAR       33339
#define ID_PLAYLIST_VIEW_ARTIST         33340
#define ID_PLAYLIST_VIEW_ALBUM          33341
#define ID_PLAYLIST_SELECT_CHANGE       33342

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        540
#define _APS_NEXT_COMMAND_VALUE         33343
#define _APS_NEXT_CONTROL_VALUE         1187
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
