/* Scintilla source code edit control */
/** @file SciLexer.h
 ** Interface to the added lexer functions in the SciLexer version of the edit control.
 **/
/* Copyright 1998-2002 by Neil Hodgson <neilh@scintilla.org>
 * The License.txt file describes the conditions under which this software may be distributed. */

/* Most of this file is automatically generated from the Scintilla.iface interface definition
 * file which contains any comments about the definitions. HFacer.py does the generation. */

#ifndef SCILEXER_H
#define SCILEXER_H

/* SciLexer features - not in standard Scintilla */

/* ++Autogenerated -- start of section automatically generated from Scintilla.iface */
#define SCLEX_CONTAINER 0
#define SCLEX_NULL 1
#define SCLEX_LYRIC 201
#define SCLEX_AUTOMATIC 1000
#define SCE_LYRIC_DEFAULT 0
#define SCE_LYRIC_TIMETAG 1
#define SCE_LYRIC_TIME_TAG_KEYWORD 2
#define SCE_LYRIC_TEXT 3
#define SCE_LYRIC_SEPARATOR 4
#define SCE_LYRIC_TRANSLATION 5
/* --Autogenerated -- end of section automatically generated from Scintilla.iface */

#endif
